begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select plan(15);
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values('00000000-0000-0000-0000-000000000000','73000000-0000-4000-8000-000000000001','authenticated','authenticated','pricing-owner@example.test','',now(),'{}','{"display_name":"Pricing Owner"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"73000000-0000-4000-8000-000000000001","role":"authenticated","email":"pricing-owner@example.test","aal":"aal2"}',true);
select lives_ok($$select * from app.create_business_with_owner('Pricing Test','pricing-test','Main','main','America/Chicago')$$,'tenant created');
select lives_ok($$select app.create_customer_household_with_pet((select id from businesses where public_slug='pricing-test'),'Pat','Owner','','pat@example.test',null,'Milo','Mix','2020-01-01',false,'male')$$,'pet created');
select lives_ok($$select app.create_service_draft((select id from businesses where public_slug='pricing-test'),'boarding','Boarding','Boarding','overnight_date_range',null,'instant','Stay')$$,'service created');
select lives_ok($$select app.publish_service_version((select business_id from services),(select id from services),(select id from service_versions),(select id from locations),false,true,true,false)$$,'service published');
select lives_ok($$select * from app.create_pricing_bundle((select id from businesses where public_slug='pricing-test'),(select id from locations),'Standard USD','USD','Standard policy','percentage',2500,800,24,5000,10000,'Care agreement','I agree to the disclosed care and cancellation terms.','25% deposit; 24-hour cancellation notice.')$$,'pricing bundle created');
select lives_ok($$select app.add_price_rate((select business_id from price_books),(select id from price_book_versions),(select id from locations),(select id from service_versions),'night',10000,'Boarding night',100,null,null)$$,'rate added');
select lives_ok($$select app.publish_pricing_bundle((select business_id from price_books),(select id from price_book_versions),(select id from commercial_policy_versions),current_date)$$,'pricing published');
select lives_ok($$select app.calculate_quote((select business_id from price_books),(select id from locations),(select id from pets),(select id from services),now()+interval '1 day',now()+interval '4 days',2,3,'quote-request-001')$$,'quote calculated');
select is((select subtotal_minor from quotes),60000::bigint,'subtotal reconciles');
select is((select tax_minor from quotes),4800::bigint,'tax uses basis points and half-up rounding');
select is((select total_minor from quotes),64800::bigint,'total reconciles');
select is((select deposit_due_minor from quotes),16200::bigint,'percentage deposit is amount timing');
select is((select balance_due_minor from quotes),48600::bigint,'remaining balance reconciles');
select is((select count(*) from quote_lines),2::bigint,'quote retains itemized base and tax lines');
select lives_ok($$select app.accept_quote_agreement((select business_id from quotes),(select id from quotes),'{"method":"staff_attested","displayed":true}')$$,'versioned agreement acceptance is retained');
select * from finish();rollback;
