begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select plan(29);
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values('00000000-0000-0000-0000-000000000000','74000000-0000-4000-8000-000000000001','authenticated','authenticated','pricing-revision@example.test','',now(),'{}','{"display_name":"Pricing Owner"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"74000000-0000-4000-8000-000000000001","role":"authenticated","email":"pricing-revision@example.test","aal":"aal2"}',true);
select lives_ok($$select * from app.create_business_with_owner('Pricing Revision Test','pricing-revision-test','Main','main','America/Chicago')$$,'tenant created');
select lives_ok($$select app.create_customer_household_with_pet((select id from businesses where public_slug='pricing-revision-test'),'Pat','Owner','','pat@example.test',null,'Milo','Mix','2020-01-01',false,'male')$$,'pet created');
select lives_ok($$select app.create_service_draft((select id from businesses where public_slug='pricing-revision-test'),'boarding','Boarding','Boarding','overnight_date_range',null,'instant','Stay')$$,'service created');
select lives_ok($$select app.publish_service_version((select business_id from services),(select id from services),(select id from service_versions),(select id from locations),false,true,true,false)$$,'service published');
select lives_ok($$select * from app.create_pricing_bundle((select id from businesses where public_slug='pricing-revision-test'),(select id from locations),'Standard USD','USD','Standard policy','percentage',2500,800,24,5000,10000,'Care agreement','I agree to the disclosed care and cancellation terms.','25% deposit; 24-hour cancellation notice.')$$,'pricing bundle created');
select lives_ok($$select app.add_price_rate((select business_id from price_books),(select id from price_book_versions),(select id from locations),(select id from service_versions),'night',10000,'Boarding night',100,null,null)$$,'base rate added');
select lives_ok($$select app.add_price_adjustment((select business_id from price_books),(select id from price_book_versions),(select id from locations),(select id from service_versions),'peak','percentage',1000,'Peak demand',100,null,null,null)$$,'adjustment added');
select lives_ok($$select app.add_discount_code((select business_id from price_books),(select id from price_book_versions),'WELCOME10','percentage',1000,'Welcome discount',0,null,10)$$,'coupon added');
select lives_ok($$select app.publish_pricing_bundle((select business_id from price_books),(select id from price_book_versions),(select id from commercial_policy_versions),current_date)$$,'pricing published');
select lives_ok($$select app.calculate_quote_with_adjustments((select business_id from price_books),(select id from locations),(select id from pets),(select id from services),now()+interval '1 day',now()+interval '3 days',1,2,'adjusted-quote','welcome10',null)$$,'adjusted quote calculated');
select is((select subtotal_minor from quotes),20000::bigint,'base subtotal retained');
select is((select fee_minor from quotes),2000::bigint,'peak adjustment applied');
select is((select discount_minor from quotes),2200::bigint,'coupon applies after adjustment');
select is((select tax_minor from quotes),1584::bigint,'tax applies after discount');
select is((select total_minor from quotes),21384::bigint,'adjusted total reconciles');
select is((select count(*) from quote_lines),4::bigint,'itemized quote includes base adjustment discount and tax');
select is((select count(*) from coupon_redemptions),1::bigint,'redemption snapshot retained');
select lives_ok($$select * from app.create_pricing_revision((select business_id from price_books),(select id from price_book_versions where status='published'),(select id from commercial_policy_versions where status='published'))$$,'revision cloned');
select is((select count(*) from price_rate_rules),2::bigint,'rate cloned into revision');
select is((select count(*) from price_adjustment_rules),2::bigint,'adjustment cloned into revision');
select is((select count(*) from discount_rules),2::bigint,'discount cloned into revision');
select lives_ok($$select app.publish_pricing_bundle((select business_id from price_books),(select id from price_book_versions where status='draft'),(select id from commercial_policy_versions where status='draft'),current_date+1)$$,'revision publication supersedes prior versions');
select is((select count(*) from price_book_versions where status='published'),1::bigint,'only one price version remains published');
select lives_ok($$select app.calculate_cancellation_outcome((select business_id from quotes),(select id from quotes),'no_show',starts_at,null,null) from quotes$$,'no-show outcome snapshotted');
select is((select fee_minor from cancellation_outcomes),10000::bigint,'published no-show fee applied');
select throws_ok($$select app.calculate_quote_with_adjustments((select business_id from price_books),(select id from locations),(select id from pets),(select id from services),now()+interval '1 day',now()+interval '3 days',1,2,'invalid-coupon','NOTREAL',null)$$,'P0002','coupon unavailable','unknown coupon is rejected safely');
select throws_ok($$select app.calculate_cancellation_outcome((select business_id from quotes),(select id from quotes),'cancellation',now(),100,'short') from quotes$$,'42501','manager override requires permission and reason','override requires a meaningful reason');
select lives_ok($$select app.calculate_cancellation_outcome((select business_id from quotes),(select id from quotes),'cancellation',now(),100,'Customer service recovery') from quotes$$,'authorized override is snapshotted');
select is((select fee_minor from cancellation_outcomes where override_applied),100::bigint,'override amount retained separately');
select * from finish();rollback;
