begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select plan(30);
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values('00000000-0000-0000-0000-000000000000','75000000-0000-4000-8000-000000000001','authenticated','authenticated','booking-owner@example.test','',now(),'{}','{"display_name":"Booking Owner"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"75000000-0000-4000-8000-000000000001","role":"authenticated","email":"booking-owner@example.test","aal":"aal2"}',true);
select lives_ok($$select * from app.create_business_with_owner('Booking Test','booking-test','Main','main','America/Chicago')$$,'tenant created');
select lives_ok($$select app.create_customer_household_with_pet((select id from businesses where public_slug='booking-test'),'Pat','Owner','','pat@example.test',null,'Milo','Mix','2020-01-01',false,'male')$$,'customer household and pet created');
select lives_ok($$select app.create_service_draft((select id from businesses where public_slug='booking-test'),'boarding','Boarding','Boarding','overnight_date_range',null,'instant','Stay')$$,'service created');
select lives_ok($$select app.publish_service_version((select business_id from services),(select id from services),(select id from service_versions),(select id from locations),false,true,true,false)$$,'service published');
select lives_ok($$select app.configure_capacity_pool((select business_id from services),(select id from locations),(select id from services),'Boarding capacity','count',1,1)$$,'capacity configured');
select lives_ok($$select * from app.create_pricing_bundle((select id from businesses where public_slug='booking-test'),(select id from locations),'Standard USD','USD','Standard policy','none',0,0,24,5000,10000,'Care agreement','I agree to the disclosed care and cancellation terms.','No deposit; 24-hour cancellation notice.')$$,'pricing bundle created');
select lives_ok($$select app.add_price_rate((select business_id from price_books),(select id from price_book_versions),(select id from locations),(select id from service_versions),'night',10000,'Boarding night',100,null,null)$$,'rate added');
select lives_ok($$select app.publish_pricing_bundle((select business_id from price_books),(select id from price_book_versions),(select id from commercial_policy_versions),current_date)$$,'pricing published');
select lives_ok($$select app.create_booking_request((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,2,null,'staff','booking-001')$$,'booking request created');
select is((select status from bookings),'confirmed','zero-deposit instant request confirms');
select matches((select booking_number from bookings),'^PC-[0-9]{6}$','business booking number allocated');
select is((select count(*) from booking_revisions),1::bigint,'immutable revision retained');
select is((select count(*) from booking_items where status='confirmed'),1::bigint,'confirmed service item retained');
select is((select count(*) from capacity_holds where status='converted'),1::bigint,'capacity hold converted');
select is((select count(*) from capacity_commitments where status='active'),1::bigint,'capacity commitment active');
select is((select count(*) from booking_validation_results),5::bigint,'orchestration checks snapshotted');
select is((select count(*) from booking_timeline_events),2::bigint,'request and confirmation timeline retained');
select is(app.create_booking_request((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,2,null,'staff','booking-001'),(select id from bookings),'duplicate request is idempotent');
select throws_ok($$select app.create_booking_request((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,2,null,'staff','booking-002')$$,'P0001','booking requirements or capacity unavailable','concurrent oversell is rejected');
select lives_ok($$select app.create_waitlist_entry((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,2,'waitlist-001')$$,'eligible unmet demand joins waitlist');
select is((select status from waitlist_entries),'active','waitlist state is explicit');
select is((select flexibility_days from waitlist_entries),2,'waitlist flexibility retained');
select lives_ok($$select app.cancel_booking((select business_id from bookings),(select id from bookings),'Customer plans changed','cancel-001')$$,'confirmed booking cancels');
select is((select status from bookings),'cancelled','booking cancellation state retained');
select is((select count(*) from capacity_commitments where status='released'),1::bigint,'cancellation releases committed capacity');
select is((select count(*) from cancellation_outcomes),1::bigint,'policy outcome snapshotted');
select is((select count(*) from booking_revisions),2::bigint,'cancellation creates a new revision');
select is(app.cancel_booking((select business_id from bookings),(select id from bookings),'Customer plans changed','cancel-001'),(select id from booking_revisions where revision_number=2),'cancellation retry is idempotent');
select lives_ok($$select app.withdraw_waitlist_entry((select business_id from waitlist_entries),(select id from waitlist_entries),'Customer no longer needs the dates')$$,'active waitlist entry withdraws');
select is((select status from waitlist_entries),'withdrawn','withdrawal remains explicit and auditable');
select * from finish();rollback;
