begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select plan(41);
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values('00000000-0000-0000-0000-000000000000','76000000-0000-4000-8000-000000000001','authenticated','authenticated','workflow-owner@example.test','',now(),'{}','{"display_name":"Workflow Owner"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"76000000-0000-4000-8000-000000000001","role":"authenticated","email":"workflow-owner@example.test","aal":"aal2"}',true);
select lives_ok($$select * from app.create_business_with_owner('Workflow Test','workflow-test','Main','main','America/Chicago')$$,'tenant created');
select lives_ok($$select app.create_customer_household_with_pet((select id from businesses where public_slug='workflow-test'),'Pat','Owner','','pat@example.test',null,'Milo','Mix','2020-01-01',false,'male')$$,'customer household and pet created');
select lives_ok($$select app.create_service_draft((select id from businesses where public_slug='workflow-test'),'boarding','Boarding','Boarding','overnight_date_range',null,'staff_approval','Stay')$$,'approval service created');
select lives_ok($$select app.publish_service_version((select business_id from services),(select id from services),(select id from service_versions),(select id from locations),false,true,true,false)$$,'service published');
select lives_ok($$select app.configure_capacity_pool((select business_id from services),(select id from locations),(select id from services),'Boarding capacity','count',1,1)$$,'capacity configured');
select lives_ok($$select * from app.create_pricing_bundle((select id from businesses where public_slug='workflow-test'),(select id from locations),'Standard USD','USD','Standard policy','none',0,0,24,5000,10000,'Care agreement','I agree to the disclosed care and cancellation terms.','No deposit; 24-hour cancellation notice.')$$,'pricing created');
select lives_ok($$select app.add_price_rate((select business_id from price_books),(select id from price_book_versions),(select id from locations),(select id from service_versions),'night',10000,'Boarding night',100,null,null)$$,'rate added');
select lives_ok($$select app.publish_pricing_bundle((select business_id from price_books),(select id from price_book_versions),(select id from commercial_policy_versions),current_date)$$,'pricing published');
select lives_ok($$select app.create_booking_request((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,2,null,'staff','approval-booking')$$,'approval request created');
select is((select status from bookings),'pending_approval','request does not masquerade as confirmed');
select lives_ok($$select app.resolve_booking_review((select business_id from bookings),(select id from bookings),'approved','Manager reviewed all requirements','approval-001')$$,'manager approves request');
select is((select status from bookings),'confirmed','approved zero-deposit request confirms');
select is((select current_revision_number from bookings),2,'approval advances revision');
select is((select count(*) from booking_actions),1::bigint,'review decision retained');
select is((select count(*) from booking_changes where change_type='approval'),1::bigint,'approval change links revisions');
select is((select count(*) from capacity_commitments where status='active'),1::bigint,'approval converts capacity');
select is(app.resolve_booking_review((select business_id from bookings),(select id from bookings),'approved','Manager reviewed all requirements','approval-001'),(select id from booking_actions),'approval retry is idempotent');
select lives_ok($$select app.reschedule_booking((select business_id from bookings),(select id from bookings),now()+interval '5 days',now()+interval '7 days',2,null,'Customer requested later dates','reschedule-001')$$,'confirmed booking reschedules');
select is((select current_revision_number from bookings),3,'reschedule advances revision');
select is((select count(*) from capacity_commitments where status='released'),1::bigint,'old capacity releases after replacement commits');
select is((select count(*) from capacity_commitments where status='active'),1::bigint,'replacement commitment remains active');
select is((select count(*) from booking_items where status='cancelled'),2::bigint,'superseded items remain in revision history');
select is((select supersedes_quote_id from quotes where supersedes_quote_id is not null),(select id from quotes where supersedes_quote_id is null),'new quote links predecessor');
select is((select count(*) from booking_changes where change_type='reschedule'),1::bigint,'reschedule change retained');
select is(app.reschedule_booking((select business_id from bookings),(select id from bookings),now()+interval '5 days',now()+interval '7 days',2,null,'Customer requested later dates','reschedule-001'),(select id from booking_revisions where revision_number=3),'reschedule retry is idempotent');
select lives_ok($$select app.create_waitlist_entry((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,1,'waitlist-offer-001')$$,'waitlist demand created');
select lives_ok($$select app.offer_waitlist_entry((select business_id from waitlist_entries),(select id from waitlist_entries),30,'offer-001')$$,'available demand receives timed offer');
select is((select status from waitlist_entries),'offered','entry reflects active offer');
select is((select count(*) from waitlist_offers where status='offered'),1::bigint,'offer state retained');
select is((select count(*) from capacity_holds where status='active'),1::bigint,'offer owns active capacity hold');
select lives_ok($$select app.accept_waitlist_offer((select business_id from waitlist_offers),(select id from waitlist_offers),2,null,'accept-001')$$,'offer converts after revalidation');
select is((select status from waitlist_offers),'accepted','offer acceptance retained');
select is((select status from waitlist_entries),'converted','waitlist entry closes as converted');
select is((select count(*) from bookings),2::bigint,'conversion creates one additional booking');
select is((select source_channel from bookings where source_channel='waitlist'),'waitlist','booking source remains attributable');
select is((select status from bookings where source_channel='waitlist'),'pending_approval','conversion respects service confirmation mode');
select lives_ok($$select app.create_waitlist_entry((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '8 days',now()+interval '10 days',1,0,'waitlist-offer-002')$$,'second waitlist demand created');
select lives_ok($$select app.offer_waitlist_entry((select business_id from waitlist_entries where status='active'),(select id from waitlist_entries where status='active'),30,'offer-002')$$,'second offer created');
select lives_ok($$select app.decline_waitlist_offer((select business_id from waitlist_offers where status='offered'),(select id from waitlist_offers where status='offered'),'Customer declined the dates')$$,'offer declines safely');
select is((select status from waitlist_entries where id=(select waitlist_entry_id from waitlist_offers where status='declined')),'active','declined entry returns to active queue');
select is((select count(*) from capacity_holds where status='released'),1::bigint,'declined offer releases its hold');
select * from finish();rollback;
