begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select plan(30);
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values('00000000-0000-0000-0000-000000000000','78000000-0000-4000-8000-000000000001','authenticated','authenticated','payment-owner@example.test','',now(),'{}','{"display_name":"Payment Owner"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"78000000-0000-4000-8000-000000000001","role":"authenticated","email":"payment-owner@example.test","aal":"aal2"}',true);
select lives_ok($$select * from app.create_business_with_owner('Payment Test','payment-test','Main','main','America/Chicago')$$,'tenant created');
select lives_ok($$select app.create_customer_household_with_pet((select id from businesses where public_slug='payment-test'),'Pat','Owner','','payment@example.test',null,'Milo','Mix','2020-01-01',false,'male')$$,'customer and pet created');
select lives_ok($$select app.create_service_draft((select id from businesses where public_slug='payment-test'),'boarding','Boarding','Boarding','overnight_date_range',null,'staff_approval','Stay')$$,'service created');
select lives_ok($$select app.publish_service_version((select business_id from services),(select id from services),(select id from service_versions),(select id from locations),false,true,true,false)$$,'service published');
select lives_ok($$select app.configure_capacity_pool((select business_id from services),(select id from locations),(select id from services),'Boarding capacity','count',2,2)$$,'capacity configured');
select lives_ok($$select * from app.create_pricing_bundle((select id from businesses where public_slug='payment-test'),(select id from locations),'Standard USD','USD','Deposit policy','percentage',5000,0,24,5000,10000,'Care agreement','Accepted payment terms.','Fifty percent deposit.')$$,'pricing created');
select lives_ok($$select app.add_price_rate((select business_id from price_books),(select id from price_book_versions),(select id from locations),(select id from service_versions),'night',10000,'Boarding night',100,null,null)$$,'rate created');
select lives_ok($$select app.publish_pricing_bundle((select business_id from price_books),(select id from price_book_versions),(select id from commercial_policy_versions),current_date)$$,'pricing published');
select lives_ok($$select app.create_booking_request((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,2,null,'staff','payment-booking')$$,'booking requested');
select lives_ok($$select app.resolve_booking_review((select business_id from bookings),(select id from bookings),'approved','Manager approved the request','payment-approval')$$,'booking approved');
select is((select status from bookings),'pending_deposit','deposit still blocks confirmation');
select lives_ok($$select app.issue_booking_invoice((select business_id from bookings),(select id from bookings),'invoice-001')$$,'invoice issued');
select is(app.issue_booking_invoice((select business_id from bookings),(select id from bookings),'invoice-001'),(select id from invoices),'invoice retry is idempotent');
select is((select status from invoices),'open','invoice is open');
select is((select total_minor from invoice_balances),20000::bigint,'invoice total matches quote');
select is((select deposit_required_minor from invoice_balances),10000::bigint,'deposit requirement matches quote');
select is((select count(*) from invoice_lines),(select count(*) from quote_lines),'invoice copies every quote line');
select is((select count(*) from transactional_message_outbox where message_type='invoice_issued'),1::bigint,'invoice email queued once');
select throws_ok($$select app.record_manual_payment((select business_id from invoices),(select id from invoices),(select location_id from invoices),20001,'cash','','too-large')$$,'22023','collectible invoice unavailable','overpayment rejected');
select lives_ok($$select app.record_manual_payment((select business_id from invoices),(select id from invoices),(select location_id from invoices),10000,'check','CHECK-1001','deposit-001')$$,'deposit posted');
select is(app.record_manual_payment((select business_id from invoices),(select id from invoices),(select location_id from invoices),10000,'check','CHECK-1001','deposit-001'),(select id from payments),'payment retry is idempotent');
select is((select status from invoices),'partially_paid','partial invoice state derived');
select is((select paid_minor from invoice_balances),10000::bigint,'allocation updates paid amount');
select is((select balance_due_minor from invoice_balances),10000::bigint,'remaining balance is correct');
select is((select status from bookings),'confirmed','fully allocated deposit confirms booking');
select is((select count(*) from receipts),1::bigint,'receipt retained');
select is((select count(*) from transactional_message_outbox where message_type='payment_receipt'),1::bigint,'receipt email queued once');
select lives_ok($$select app.record_manual_payment((select business_id from invoices),(select id from invoices),(select location_id from invoices),10000,'cash','','balance-001')$$,'remaining balance posted');
select is((select status from invoices),'paid','invoice closes only when fully allocated');
select is((select balance_due_minor from invoice_balances),0::bigint,'paid invoice balances to zero');
select * from finish();rollback;
