begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select plan(20);
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values('00000000-0000-0000-0000-000000000000','79000000-0000-4000-8000-000000000001','authenticated','authenticated','merchant-owner@example.test','',now(),'{}','{"display_name":"Merchant Owner"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"79000000-0000-4000-8000-000000000001","role":"authenticated","email":"merchant-owner@example.test","aal":"aal2"}',true);
select lives_ok($$select * from app.create_business_with_owner('Merchant Test','merchant-test','Main','main','America/Chicago')$$,'tenant created');
select ok(app.member_has_permission((select id from businesses where public_slug='merchant-test'),'payments.manage'),'owner receives merchant permission');
select throws_ok($$select app.configure_stripe_merchant_account((select id from businesses where public_slug='merchant-test'),'acct_MerchantOne','express')$$,'42501',null,'tenant user cannot self-assert merchant ownership');
set local role service_role;
select throws_ok($$select app.configure_stripe_merchant_account((select id from businesses where public_slug='merchant-test'),'sk_test_secret','express')$$,'22023','invalid merchant account reference','secret cannot be stored as account reference');
select lives_ok($$select app.configure_stripe_merchant_account((select id from businesses where public_slug='merchant-test'),'acct_MerchantOne','express')$$,'verified onboarding service maps merchant');
select is((select requirements_collector from merchant_accounts),'stripe','Stripe collects requirements');
select is((select losses_payer from merchant_accounts),'stripe','Stripe retains connected-account loss responsibility');
select is((select status from merchant_accounts),'pending','manual reference cannot claim active capability');
select lives_ok($$select app.ingest_stripe_webhook('evt_mapped','payment_intent.succeeded','acct_MerchantOne','pi_123','2026-01-28.clover',false,'{"id":"evt_mapped","object":"event"}','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',1700000000)$$,'mapped verified event ingested');
select is(app.ingest_stripe_webhook('evt_mapped','payment_intent.succeeded','acct_MerchantOne','pi_123','2026-01-28.clover',false,'{"id":"evt_mapped","object":"event"}','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',1700000000),(select id from processor_webhook_events where provider_event_id='evt_mapped'),'duplicate event returns one inbox record');
select lives_ok($$select app.ingest_stripe_webhook('evt_unknown','payment_intent.succeeded','acct_Unknown','pi_999','2026-01-28.clover',false,'{"id":"evt_unknown","object":"event"}','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',1700000001)$$,'unknown account event retained');
select is((select count(*) from processor_webhook_events),2::bigint,'provider event id deduplicates inbox');
select is((select status from processor_webhook_events where provider_event_id='evt_mapped'),'pending','mapped event awaits asynchronous processing');
select is((select business_id from processor_webhook_events where provider_event_id='evt_mapped'),(select business_id from merchant_accounts),'merchant maps event to one tenant');
select is((select status from processor_webhook_events where provider_event_id='evt_unknown'),'quarantined','unknown account quarantined');
select is((select quarantine_reason from processor_webhook_events where provider_event_id='evt_unknown'),'merchant_account_unmapped','quarantine is explainable');
select is((select count(*) from processor_webhook_payloads),2::bigint,'raw verified payload retained separately');
select is((select count(*) from processor_webhook_events where payload_sha256 in(repeat('a',64),repeat('b',64))),2::bigint,'payload hashes retained');
set local role authenticated;
select is((select count(*) from processor_webhook_events),1::bigint,'tenant sees only its mapped event metadata');
select throws_ok($$select raw_payload from processor_webhook_payloads$$,'42501',null,'tenant cannot read raw processor payload');
select * from finish();rollback;
