begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select plan(27);
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values('00000000-0000-0000-0000-000000000000','81000000-0000-4000-8000-000000000001','authenticated','authenticated','checkout-owner@example.test','',now(),'{}','{"display_name":"Checkout Owner"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"81000000-0000-4000-8000-000000000001","role":"authenticated","email":"checkout-owner@example.test","aal":"aal2"}',true);
select lives_ok($$select * from app.create_business_with_owner('Checkout Test','checkout-test','Main','main','America/Chicago')$$,'tenant created');
select lives_ok($$select app.create_customer_household_with_pet((select id from businesses where public_slug='checkout-test'),'Pat','Owner','','checkout@example.test',null,'Milo','Mix','2020-01-01',false,'male')$$,'customer created');
select lives_ok($$select app.create_service_draft((select id from businesses where public_slug='checkout-test'),'boarding','Boarding','Boarding','overnight_date_range',null,'staff_approval','Stay')$$,'service created');
select lives_ok($$select app.publish_service_version((select business_id from services),(select id from services),(select id from service_versions),(select id from locations),false,true,true,false)$$,'service published');
select lives_ok($$select app.configure_capacity_pool((select business_id from services),(select id from locations),(select id from services),'Capacity','count',2,2)$$,'capacity configured');
select lives_ok($$select * from app.create_pricing_bundle((select id from businesses where public_slug='checkout-test'),(select id from locations),'USD','USD','Deposit','percentage',5000,0,24,5000,10000,'Agreement','Accepted payment terms.','Half deposit.')$$,'pricing configured');
select lives_ok($$select app.add_price_rate((select business_id from price_books),(select id from price_book_versions),(select id from locations),(select id from service_versions),'night',10000,'Night',100,null,null)$$,'rate created');
select lives_ok($$select app.publish_pricing_bundle((select business_id from price_books),(select id from price_book_versions),(select id from commercial_policy_versions),current_date)$$,'pricing published');
select lives_ok($$select app.create_booking_request((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,2,null,'staff','checkout-booking')$$,'booking requested');
select lives_ok($$select app.resolve_booking_review((select business_id from bookings),(select id from bookings),'approved','Manager approved checkout test','checkout-approval')$$,'booking approved');
select lives_ok($$select app.issue_booking_invoice((select business_id from bookings),(select id from bookings),'checkout-invoice')$$,'invoice issued');
set local role service_role;select lives_ok($$select app.sync_stripe_merchant_account((select id from businesses where public_slug='checkout-test'),'acct_Checkout',true,true,true,'{"card_payments":"active"}','[]','')$$,'merchant activated');set local role authenticated;
select lives_ok($$select app.create_stripe_payment_request((select business_id from invoices),(select id from invoices),10000,'checkout-request')$$,'online payment request created');
select is(app.create_stripe_payment_request((select business_id from invoices),(select id from invoices),10000,'checkout-request'),(select id from payment_requests),'request retry is idempotent');
set local role service_role;select lives_ok($$select app.attach_stripe_checkout_session((select id from payment_requests),'cs_test_checkout')$$,'checkout session attached');
select lives_ok($$select app.ingest_stripe_webhook('evt_checkout','checkout.session.completed','acct_Checkout','cs_test_checkout','2026-01-28.clover',false,jsonb_build_object('id','evt_checkout','type','checkout.session.completed','data',jsonb_build_object('object',jsonb_build_object('id','cs_test_checkout','payment_status','paid','amount_total',10000,'currency','usd','payment_intent','pi_checkout','metadata',jsonb_build_object('petcare_payment_request_id',(select id from payment_requests)::text)))),'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',1700000002)$$,'verified completion ingested');
select lives_ok($$select app.process_stripe_checkout_event((select id from processor_webhook_events))$$,'completion posted');
select is(app.process_stripe_checkout_event((select id from processor_webhook_events)),(select id from payments),'posting retry is idempotent');
select is((select status from payment_requests),'succeeded','request succeeds from verified event');
select is((select count(*) from payments),1::bigint,'one payment posted');
select is((select count(*) from payment_allocations),1::bigint,'one allocation posted');
select is((select paid_minor from invoice_balances),10000::bigint,'invoice allocation balances');
select is((select status from invoices),'partially_paid','deposit leaves remaining balance');
select is((select status from bookings),'confirmed','paid deposit confirms booking');
select is((select count(*) from receipts),1::bigint,'receipt created');
select is((select count(*) from transactional_message_outbox where message_type='payment_receipt'),1::bigint,'receipt delivery queued');
select is((select status from processor_webhook_events),'processed','event closes after posting');
select * from finish();rollback;
