begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select plan(304);
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values('00000000-0000-0000-0000-000000000000','82000000-0000-4000-8000-000000000001','authenticated','authenticated','checkin-owner@example.test','',now(),'{}','{"display_name":"Check-in Owner"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"82000000-0000-4000-8000-000000000001","role":"authenticated","email":"checkin-owner@example.test","aal":"aal2"}',true);
select lives_ok($$select * from app.create_business_with_owner('Check-in Test','checkin-test','Main','main','America/Chicago')$$,'tenant created');
select lives_ok($$select app.create_customer_household_with_pet((select id from businesses where public_slug='checkin-test'),'Pat','Owner','','checkin@example.test',null,'Milo','Mixed breed','2020-01-01',false,'male')$$,'customer and pet created');
select lives_ok($$select app.create_service_draft((select id from businesses where public_slug='checkin-test'),'boarding','Boarding','Boarding','overnight_date_range',null,'staff_approval','Stay')$$,'service created');
select lives_ok($$select app.publish_service_version((select business_id from services),(select id from services),(select id from service_versions),(select id from locations),false,true,true,false)$$,'service published');
select lives_ok($$select app.configure_capacity_pool((select business_id from services),(select id from locations),(select id from services),'Capacity','count',2,2)$$,'capacity configured');
insert into capacity_resources(business_id,capacity_pool_id,resource_code,label,resource_type,max_pets) values((select business_id from capacity_pools),(select id from capacity_pools),'K-01','Kennel 01','kennel',1);
select lives_ok($$select * from app.create_pricing_bundle((select id from businesses where public_slug='checkin-test'),(select id from locations),'USD','USD','Deposit','percentage',5000,0,24,5000,10000,'Agreement','Accepted payment terms.','Half deposit.')$$,'pricing configured');
select lives_ok($$select app.add_price_rate((select business_id from price_books),(select id from price_book_versions),(select id from locations),(select id from service_versions),'night',10000,'Night',100,null,null)$$,'rate created');
select lives_ok($$select app.publish_pricing_bundle((select business_id from price_books),(select id from price_book_versions),(select id from commercial_policy_versions),current_date)$$,'pricing published');
select lives_ok($$select app.create_booking_request((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,2,null,'staff','checkin-booking')$$,'booking requested');
select lives_ok($$select app.resolve_booking_review((select business_id from bookings),(select id from bookings),'approved','Manager approved check-in test','checkin-approval')$$,'booking approved');
select lives_ok($$select app.issue_booking_invoice((select business_id from bookings),(select id from bookings),'checkin-invoice')$$,'invoice issued');
select lives_ok($$select app.record_manual_payment((select business_id from invoices),(select id from invoices),(select location_id from invoices),10000,'check','CHECK-IN','checkin-deposit')$$,'deposit posted');
select is((select status from bookings),'confirmed','deposit confirms booking');
select lives_ok($$select app.record_booking_arrival((select business_id from bookings),(select id from bookings),'arrival-once')$$,'arrival recorded');
select is(app.record_booking_arrival((select business_id from bookings),(select id from bookings),'arrival-retry'),(select id from operational_visits),'arrival retry returns same visit');
select is((select count(*) from operational_visits),1::bigint,'one operational visit created');
select is((select status from operational_visits),'arrived','arrival remains distinct from check-in');
select is((select status from pet_visits),'arrived','pet is physically arrived');
insert into booking_action_items(business_id,booking_id,booking_revision_id,action_type,audience,title,metadata) values((select business_id from bookings),(select id from bookings),(select id from booking_revisions order by revision_number desc limit 1),'intake','manager','Review changed arrival instruction','{"overrideable":true}');
select throws_ok($$select app.complete_pet_check_in((select business_id from bookings),(select id from bookings),(select id from pets),'Pat Owner','owner','photo_id','["name:Milo","breed:Mixed breed"]','{}','[]','blocked-checkin')$$,'P0001','blocking booking actions remain open','open action blocks custody acceptance');
select lives_ok($$select app.resolve_check_in_blocker((select business_id from bookings),(select id from booking_action_items),'approved_exception','Manager verified a safe visit-only exception','{"review":"completed"}','resolve-intake')$$,'manager resolves policy-marked blocker');
select is((select status from booking_action_items where title='Review changed arrival instruction'),'resolved','resolved blocker closes explicitly');
select is(app.resolve_check_in_blocker((select business_id from bookings),(select id from booking_action_items),'approved_exception','Manager verified a safe visit-only exception','{}','resolve-intake'),(select id from check_in_blocker_resolutions),'resolution retry is idempotent');
select is((select count(*) from check_in_blocker_resolutions),1::bigint,'one blocker resolution retained');
select throws_ok($$update check_in_blocker_resolutions set reason='rewritten evidence'$$,'P0001','commercial snapshots are immutable','manager resolution cannot be rewritten');
select lives_ok($$select app.complete_pet_check_in((select business_id from bookings),(select id from bookings),(select id from pets),'Pat Owner','owner','photo_id','["name:Milo","breed:Mixed breed"]','{"notes":"No visible concerns"}','[{"category":"belonging","name":"Blue leash","quantity":1,"unit":"item","storage":"Cubby A","return_expected":true}]','checkin-once')$$,'custody accepted');
select is(app.complete_pet_check_in((select business_id from bookings),(select id from bookings),(select id from pets),'Pat Owner','owner','photo_id','["name:Milo","breed:Mixed breed"]','{"notes":"No visible concerns"}','[]','checkin-once'),(select id from check_in_records),'check-in retry returns same record');
select is((select status from operational_visits),'in_care','visit enters care after all pets check in');
select is((select status from pet_visits),'in_care','pet enters care');
select is((select count(*) from check_in_records),1::bigint,'one immutable check-in record retained');
select is((select count(*) from care_plan_snapshots),1::bigint,'one care snapshot retained');
select is((select count(*) from visit_custody_items),1::bigint,'custody item is not duplicated');
select is((select count(*) from operational_timeline_events),2::bigint,'arrival and check-in timeline events retained');
select is((select jsonb_array_length(verified_identifiers) from check_in_records),2,'two pet identifiers preserved');
select is((select jsonb_typeof(snapshot->'medications') from care_plan_snapshots),'array','care snapshot has structured medication data');
select throws_ok($$update care_plan_snapshots set snapshot='{}'$$,'P0001','commercial snapshots are immutable','care snapshot cannot be rewritten');
select throws_ok($$select app.complete_pet_check_in((select business_id from bookings),(select id from bookings),(select id from pets),'Pat Owner','owner','photo_id','["name:Milo","name:Milo"]','{}','[]','different-key')$$,'22023','two pet identifiers are required','duplicate identity signals are rejected');
select lives_ok($$select app.accept_operational_handoff((select business_id from pet_visits),(select id from pet_visits),(select id from capacity_resources),'Blue leash is in Cubby A.','handoff-once')$$,'receiving staff accepts handoff');
select is(app.accept_operational_handoff((select business_id from pet_visits),(select id from pet_visits),(select id from capacity_resources),'Blue leash is in Cubby A.','handoff-once'),(select id from operational_handoffs),'handoff retry is idempotent');
select is((select handoff_status from pet_visits),'accepted','pet handoff state is explicit');
select is((select count(*) from visit_resource_assignments),1::bigint,'one named-resource assignment created');
select is((select status from capacity_resources),'occupied','full resource becomes occupied');
select is((select count(*) from transactional_message_outbox where message_type='pet_checked_in'),1::bigint,'customer check-in communication queued once');
select is((select count(*) from operational_timeline_events),3::bigint,'handoff appends operational timeline evidence');
select throws_ok($$select app.accept_operational_handoff((select business_id from pet_visits),(select id from pet_visits),null,'Duplicate handoff','handoff-different')$$,'P0002','pet handoff unavailable','second handoff is rejected');
select throws_ok($$update operational_handoffs set handoff_notes='rewritten'$$,'P0001','commercial snapshots are immutable','accepted handoff cannot be rewritten');
select is((select ends_at-starts_at from visit_resource_assignments),(select scheduled_end-scheduled_start from operational_visits),'resource assignment covers the visit schedule');
select lives_ok($$select app.add_visit_care_amendment((select business_id from pet_visits),(select id from pet_visits),'feeding','{"instructions":"Offer half portion at first meal"}','Customer reported mild travel appetite',true,'amendment-once')$$,'visit-only care amendment added');
select is(app.add_visit_care_amendment((select business_id from pet_visits),(select id from pet_visits),'feeding','{"instructions":"Offer half portion at first meal"}','Customer reported mild travel appetite',true,'amendment-once'),(select id from care_plan_amendments),'care amendment retry is idempotent');
select is((select count(*) from care_plan_amendments),1::bigint,'one care amendment retained');
select is((select master_update_status from care_plan_amendments),'proposed','master-profile work remains a separate proposal');
select lives_ok($$select app.schedule_snapshot_care_task((select business_id from pet_visits),(select id from pet_visits),'feeding','Breakfast','{"instructions":"Offer normal breakfast portion"}',(select scheduled_start+interval '1 hour' from operational_visits),(select scheduled_start+interval '2 hours' from operational_visits),'routine',null,'feeding-task')$$,'feeding task scheduled from active snapshot');
select is(app.schedule_snapshot_care_task((select business_id from pet_visits),(select id from pet_visits),'feeding','Breakfast','{"instructions":"Offer normal breakfast portion"}',(select scheduled_start+interval '1 hour' from operational_visits),(select scheduled_start+interval '2 hours' from operational_visits),'routine',null,'feeding-task'),(select id from care_tasks where task_type='feeding'),'task scheduling retry is idempotent');
select lives_ok($$select app.start_care_task((select business_id from care_tasks),(select id from care_tasks where task_type='feeding'),'start-feeding')$$,'feeding task started');
select lives_ok($$select app.record_care_task_outcome((select business_id from care_tasks),(select id from care_tasks where task_type='feeding'),'refused','{"observation":"Would not approach bowl"}',true,'Pet refused meal after two calm offers','feeding-outcome')$$,'feeding refusal recorded');
select is(app.record_care_task_outcome((select business_id from care_tasks),(select id from care_tasks where task_type='feeding'),'refused','{"observation":"Would not approach bowl"}',true,'Pet refused meal after two calm offers','feeding-outcome'),(select id from care_task_events where idempotency_key='feeding-outcome'),'outcome retry is idempotent');
select is((select status from care_tasks where task_type='feeding'),'refused','feeding task keeps structured refusal state');
select is((select count(*) from operational_alerts),1::bigint,'feeding refusal creates one open alert');
select is((select severity from operational_alerts),'urgent','feeding refusal escalates urgently');
select is((select count(*) from care_task_events where care_task_id=(select id from care_tasks where task_type='feeding')),4::bigint,'task retains schedule start outcome and escalation events');
select is((select count(*) from operational_timeline_events),5::bigint,'care outcome appends visit timeline evidence');
select lives_ok($$select app.schedule_snapshot_care_task((select business_id from pet_visits),(select id from pet_visits),'medication','Morning medication','{"instructions":"Give labeled oral medication"}',(select scheduled_start+interval '3 hours' from operational_visits),(select scheduled_start+interval '4 hours' from operational_visits),'critical',null,'medication-task')$$,'medication task scheduled with explicit window');
select throws_ok($$select app.record_care_task_outcome((select business_id from care_tasks),(select id from care_tasks where task_type='medication'),'completed','{"observation":"Administered","five_rights_confirmed":false}',true,'','medication-unsafe')$$,'22023','medication verification required','medication cannot complete without five-rights verification');
select lives_ok($$select app.record_care_task_outcome((select business_id from care_tasks),(select id from care_tasks where task_type='medication'),'completed','{"observation":"Administered as labeled","five_rights_confirmed":true}',true,'','medication-outcome')$$,'verified medication administration recorded');
select is((select count(*) from operational_alerts),1::bigint,'successful medication does not create false alert');
select lives_ok($$select app.record_visit_observation((select business_id from pet_visits),(select id from pet_visits),'activity','yard_play','{"observation":"Calm parallel play for fifteen minutes"}','information',true,now(),'observation-info')$$,'routine activity observation recorded');
select is(app.record_visit_observation((select business_id from pet_visits),(select id from pet_visits),'activity','yard_play','{"observation":"Calm parallel play for fifteen minutes"}','information',true,now(),'observation-info'),(select id from visit_observations where idempotency_key='observation-info'),'observation retry is idempotent');
select is((select count(*) from operational_alerts),1::bigint,'routine observation creates no alert');
select lives_ok($$select app.record_visit_observation((select business_id from pet_visits),(select id from pet_visits),'wellness','mobility','{"observation":"Sudden reluctance to bear weight"}','urgent',false,now(),'observation-urgent')$$,'urgent wellness observation recorded');
select is((select count(*) from operational_alerts),2::bigint,'urgent observation creates one alert');
select is((select severity from operational_alerts where observation_id is not null),'urgent','observation alert preserves severity');
select lives_ok($$select app.transition_operational_alert((select business_id from operational_alerts),(select id from operational_alerts where observation_id is not null),'acknowledged','')$$,'care staff acknowledges alert');
select is((select status from operational_alerts where observation_id is not null),'acknowledged','alert remains active after acknowledgement');
select lives_ok($$select app.transition_operational_alert((select business_id from operational_alerts),(select id from operational_alerts where observation_id is not null),'resolved','Owner documented follow-up and safe care plan.')$$,'owner resolves alert with evidence');
select is((select status from operational_alerts where observation_id is not null),'resolved','resolved alert closes explicitly');
select lives_ok($$select app.correct_care_task_outcome((select business_id from care_tasks),(select id from care_tasks where task_type='feeding'),'completed','{"observation":"Meal was later confirmed eaten"}','Manager reconciled the signed paper record.','feeding-correction')$$,'manager appends feeding correction');
select is(app.correct_care_task_outcome((select business_id from care_tasks),(select id from care_tasks where task_type='feeding'),'completed','{"observation":"Meal was later confirmed eaten"}','Manager reconciled the signed paper record.','feeding-correction'),(select id from care_task_corrections),'correction retry is idempotent');
select is((select count(*) from care_task_events where care_task_id=(select id from care_tasks where task_type='feeding') and event_type='outcome_recorded'),1::bigint,'original outcome event remains intact');
select is((select count(*) from care_task_events where care_task_id=(select id from care_tasks where task_type='feeding') and event_type='corrected'),1::bigint,'correction appends a distinct event');
select lives_ok($$select app.initialize_service_execution((select business_id from pet_visits),(select id from pet_visits),'execution-start')$$,'boarding execution initialized after handoff');
select is(app.initialize_service_execution((select business_id from pet_visits),(select id from pet_visits),'execution-retry'),(select id from service_executions),'execution initialization retry returns existing workflow');
select is((select stage from service_executions),'settling','boarding begins in settling');
select throws_ok($$select app.transition_service_execution((select business_id from service_executions),(select id from service_executions),'ready','Premature ready attempt','execution-invalid')$$,'22023','invalid documented service transition','boarding cannot skip required stages');
select lives_ok($$select app.transition_service_execution((select business_id from service_executions),(select id from service_executions),'active','','execution-active')$$,'boarding progresses to active care');
select lives_ok($$select app.transition_service_execution((select business_id from service_executions),(select id from service_executions),'departure_preparation','','execution-departure')$$,'boarding enters departure preparation');
select lives_ok($$select app.transition_service_execution((select business_id from service_executions),(select id from service_executions),'ready','Final care and belongings review complete.','execution-ready')$$,'documented boarding service becomes ready');
select is((select stage from service_executions),'ready','service readiness remains distinct from checkout');
select lives_ok($$select app.create_playgroup_session((select id from businesses where public_slug='checkin-test'),(select id from locations),'Morning Group','mixed',8,4,2,'playgroup-session')$$,'staffed playgroup session opens');
select is(app.create_playgroup_session((select id from businesses where public_slug='checkin-test'),(select id from locations),'Morning Group','mixed',8,4,2,'playgroup-session'),(select id from playgroup_sessions),'playgroup creation retry is idempotent');
select is((select least(max_pets,pets_per_staff*staff_count) from playgroup_sessions),8,'effective group capacity respects physical and staff limits');
select throws_ok($$select app.record_daycare_evaluation((select business_id from service_executions),(select id from service_executions),'approved','{}','Calm handling response.','wrong-service-evaluation')$$,'22023','structured daycare evaluation required','boarding execution cannot receive daycare evaluation');
select throws_ok($$select app.record_grooming_intake((select business_id from service_executions),(select id from service_executions),'Short trim','Healthy coat','No visible concerns','none','','','','false','false','wrong-service-intake')$$,'22023','structured grooming intake required','boarding execution cannot receive grooming intake');
select throws_ok($$select app.record_grooming_quality_review((select business_id from service_executions),(select id from service_executions),'passed','{"style_verified":true}','Review complete.','wrong-service-quality')$$,'22023','structured grooming quality review required','boarding execution cannot receive grooming quality review');
select is((select count(*) from role_permissions where permission_key='operations.manage_grooming' and role_key in('owner','manager','groomer')),3::bigint,'grooming controls are limited to configured operational roles');
select lives_ok($$select app.create_operational_incident((select business_id from pet_visits),(select id from pet_visits),(select id from service_executions),'injury','serious',now(),'Small superficial scrape observed on left paw.','Separated pet and completed an immediate visual check.','Manager reviewing yard surface.','A small scrape was observed and the pet is comfortable while we monitor.','incident-serious')$$,'serious incident reported with immediate actions');
select is((select severity from operational_incidents),'serious','incident preserves original severity');
select is((select status from operational_incidents),'escalated','serious incident starts escalated');
select is((select count(*) from operational_alerts),3::bigint,'serious incident adds an operational alert');
select lives_ok($$select app.transition_operational_incident((select business_id from operational_incidents),(select id from operational_incidents),'under_review','Manager reviewed immediate actions.',true,'We reviewed the scrape and continue to monitor comfort.','incident-review')$$,'incident review records customer-safe communication');
select lives_ok($$select app.transition_operational_incident((select business_id from operational_incidents),(select id from operational_incidents),'resolved','Manager confirmed monitoring completed safely.',false,'','incident-resolved')$$,'manager resolves serious incident');
select is((select status from operational_incidents),'resolved','incident reaches documented resolution');
select is((select status from operational_alerts where incident_id is not null),'resolved','incident resolution closes its linked alert');
select lives_ok($$select app.create_report_card_draft((select business_id from service_executions),(select id from service_executions),'Milo settled well and enjoyed calm supervised activities.','{"mood":"content","favorite_activity":"yard play"}','report-card-draft')$$,'report card drafted from authorized facts');
select is((select jsonb_array_length(source_snapshot->'observations') from report_card_versions),1,'only customer-visible observation enters report card source');
select is((select jsonb_array_length(source_snapshot->'customer_incidents') from report_card_versions),1,'customer-notified incident enters report card source');
select lives_ok($$select app.transition_report_card((select business_id from report_cards),(select id from report_cards),'review','Ready for manager review.','report-card-review')$$,'report card submitted for review');
select lives_ok($$select app.transition_report_card((select business_id from report_cards),(select id from report_cards),'approved','Manager verified customer-safe content.','report-card-approved')$$,'manager approves report card');
select lives_ok($$select app.transition_report_card((select business_id from report_cards),(select id from report_cards),'published','Approved for customer delivery.','report-card-published')$$,'manager publishes report card');
select is((select count(*) from transactional_message_outbox where message_type='report_card_published'),1::bigint,'published report card queues delivery once');
select throws_ok($$select app.complete_pet_checkout((select business_id from pet_visits),(select id from pet_visits),'Pat Owner','owner','photo_id','["name:Pat Owner","account verified"]',jsonb_build_array(jsonb_build_object('item_id',(select id from visit_custody_items),'status','returned','notes','Blue leash returned')),'Final care and property reviewed.',true,'checkout-once')$$,'P0001','checkout blockers remain unresolved','open care alert and balance prevent release');
select lives_ok($$select app.record_checkout_override((select business_id from pet_visits),(select id from pet_visits),'open_care','Manager reviewed the corrected meal record and remaining alert.','checkout-open-care')$$,'manager documents care exception');
select lives_ok($$select app.record_checkout_override((select business_id from pet_visits),(select id from pet_visits),'balance_due','Manager approved departure with documented balance follow-up.','checkout-balance')$$,'manager documents balance exception');
select lives_ok($$select app.complete_pet_checkout((select business_id from pet_visits),(select id from pet_visits),'Pat Owner','owner','photo_id','["name:Pat Owner","account verified"]',jsonb_build_array(jsonb_build_object('item_id',(select id from visit_custody_items),'status','returned','notes','Blue leash returned')),'Final care and property reviewed.',true,'checkout-once')$$,'authorized checkout completes');
select is(app.complete_pet_checkout((select business_id from pet_visits),(select id from pet_visits),'Pat Owner','owner','photo_id','["name:Pat Owner","account verified"]','[]','',true,'checkout-once'),(select id from check_out_records),'checkout retry returns the same record');
select is((select status from pet_visits),'checked_out','pet custody is released');
select is((select status from operational_visits),'checked_out','final pet checkout closes operational visit');
select is((select status from visit_resource_assignments),'released','active resource assignment is released');
select is((select status from capacity_resources),'cleaning','released resource requires cleaning');
select is((select count(*) from resource_turnover_tasks),1::bigint,'one turnover task is created');
select is((select return_status from custody_item_returns),'returned','custody return is preserved');
select is((select status from booking_items),'completed','booked service item completes at checkout');
select lives_ok($$select app.start_resource_turnover((select business_id from resource_turnover_tasks),(select id from resource_turnover_tasks),'turnover-start')$$,'resource cleaning starts');
select is(app.start_resource_turnover((select business_id from resource_turnover_tasks),(select id from resource_turnover_tasks),'turnover-start'),(select id from resource_turnover_events where event_type='cleaning_started'),'cleaning start retry is idempotent');
select is((select status from resource_turnover_tasks),'cleaning','turnover has explicit cleaning state');
select throws_ok($$select app.complete_resource_cleaning((select business_id from resource_turnover_tasks),(select id from resource_turnover_tasks),'{"debris_removed":true,"washed":true,"disinfected":false,"dry":true,"setup_reset":true}','Facility protocol A','Attempted incomplete cleaning','turnover-clean-incomplete')$$,'22023','required cleaning checklist incomplete','incomplete sanitation cannot advance');
select lives_ok($$select app.complete_resource_cleaning((select business_id from resource_turnover_tasks),(select id from resource_turnover_tasks),'{"debris_removed":true,"washed":true,"disinfected":true,"dry":true,"setup_reset":true}','Facility protocol A','All required surfaces completed.','turnover-clean')$$,'cleaning completion is documented');
select is((select status from resource_turnover_tasks),'inspection_required','cleaning does not directly release resource');
select lives_ok($$select app.inspect_resource_turnover((select business_id from resource_turnover_tasks),(select id from resource_turnover_tasks),false,'{"visibly_clean":true,"dry":true,"odor_free":false,"safe":true,"setup_correct":true}','Odor remains; repeat cleaning and ventilation.','turnover-inspect-failed')$$,'failed inspection is documented');
select is((select status from resource_turnover_tasks),'cleaning_required','failed inspection requires recleaning');
select is((select status from capacity_resources),'cleaning','failed resource remains unavailable');
select lives_ok($$select app.start_resource_turnover((select business_id from resource_turnover_tasks),(select id from resource_turnover_tasks),'turnover-reclean-start')$$,'recleaning starts');
select lives_ok($$select app.complete_resource_cleaning((select business_id from resource_turnover_tasks),(select id from resource_turnover_tasks),'{"debris_removed":true,"washed":true,"disinfected":true,"dry":true,"setup_reset":true}','Facility protocol A','Recleaned and ventilated.','turnover-reclean')$$,'recleaning completes');
select lives_ok($$select app.inspect_resource_turnover((select business_id from resource_turnover_tasks),(select id from resource_turnover_tasks),true,'{"visibly_clean":true,"dry":true,"odor_free":true,"safe":true,"setup_correct":true}','Independent readiness inspection passed.','turnover-inspect-passed')$$,'passed inspection releases resource');
select is((select status from capacity_resources),'ready','passed inspection restores assignment readiness');
select is((select count(*) from resource_turnover_events),5::bigint,'complete turnover history is append-only');
select lives_ok($$select app.grant_customer_portal_access((select id from businesses where public_slug='checkin-test'),(select id from customers),'82000000-0000-4000-8000-000000000001')$$,'staff explicitly grants portal authority');
select is((app.get_customer_portal_dashboard((select id from businesses where public_slug='checkin-test'))->'household'->>'display_name'),(select display_name from households),'portal resolves only the granted household');
select is(jsonb_array_length(app.get_customer_portal_dashboard((select id from businesses where public_slug='checkin-test'))->'pets'),1,'portal returns household pets');
select is(jsonb_array_length(app.get_customer_portal_dashboard((select id from businesses where public_slug='checkin-test'))->'bookings'),1,'portal returns customer bookings');
select is(jsonb_array_length(app.get_customer_portal_dashboard((select id from businesses where public_slug='checkin-test'))->'report_cards'),1,'portal returns published household report cards');
select lives_ok($$select app.submit_customer_service_request((select id from businesses where public_slug='checkin-test'),'profile_support',null,'Correct contact details','{"message":"Please review my account contact details."}','portal-request')$$,'portal customer submits a support request');
select is(app.submit_customer_service_request((select id from businesses where public_slug='checkin-test'),'profile_support',null,'Correct contact details','{"message":"Please review my account contact details."}','portal-request'),(select id from customer_service_requests),'portal request retry is idempotent');
select is((select count(*) from customer_service_request_events),1::bigint,'request submission creates one immutable event');
select lives_ok($$select app.update_portal_customer_profile((select id from businesses where public_slug='checkin-test'),'Patti','555-555-0199')$$,'portal customer updates safe profile fields');
select is((select preferred_name from customers),'Patti','preferred name update is visible');
select lives_ok($$select app.transition_customer_service_request((select business_id from customer_service_requests),(select id from customer_service_requests),'in_review','Front desk began documented review.','portal-review')$$,'staff starts request review');
select lives_ok($$select app.transition_customer_service_request((select business_id from customer_service_requests),(select id from customer_service_requests),'approved','Manager approved the requested support work.','portal-approved')$$,'staff approves request');
select is((select status from customer_service_requests),'approved','request state is explicit and separate from source records');
select lives_ok($$select app.revoke_customer_portal_access((select id from businesses where public_slug='checkin-test'),(select id from customers),'Customer requested a fresh portal invitation.')$$,'staff revokes portal access with reason');
update customers set email='checkin-owner@example.test';
select lives_ok($$select * from app.create_customer_portal_invitation((select id from businesses where public_slug='checkin-test'),(select id from customers),interval '7 days')$$,'staff creates customer portal invitation');
select is((select state from customer_portal_invitations),'pending','portal invitation starts pending');
select is((select count(*) from app.get_customer_portal_invitation_preview((select encode(token_digest,'hex') from customer_portal_invitations))),0::bigint,'stored digest cannot be used as raw invitation token');
select is((select status from customer_portal_access),'revoked','revocation preserves explicit access history');
select lives_ok($$select app.save_tenant_website_draft((select id from businesses where public_slug='checkin-test'),'modern','{"primary":"#23664f","accent":"#d97745"}','{"hero_title":"Care that feels like home","hero_body":"Safe and thoughtful care for every visit.","about":"Our team provides attentive care with clear communication.","faqs":[{"question":"What should I bring?","answer":"Bring labeled food, medication, and comfort items."}],"policies":"Vaccination and cancellation policies apply to every reservation.","contact_email":"hello@example.test","contact_phone":"555-555-0188","seo_title":"Check-in Test Pet Care","seo_description":"Boarding and care from a team you can trust."}')$$,'website draft saves');
select lives_ok($$select app.publish_tenant_website((select id from businesses where public_slug='checkin-test'),null)$$,'ready website publishes');
select is((select current_publication_number from tenant_websites),1,'first publication is numbered');
select is((app.get_public_tenant_website('checkin-test')->'content'->>'hero_title'),'Care that feels like home','public site returns published content');
select lives_ok($$select app.publish_tenant_website((select id from businesses where public_slug='checkin-test'),(select id from tenant_website_publications))$$,'rollback republishes prior snapshot');
select is((select count(*) from tenant_website_publications),2::bigint,'publication history is immutable and additive');
select lives_ok($$select app.submit_website_inquiry('checkin-test','Taylor Visitor','taylor@example.test','555-555-0100','I would like to learn more about boarding.',true,'/site/checkin-test','','inquiry-once')$$,'consented public inquiry is accepted');
select is(app.submit_website_inquiry('checkin-test','Taylor Visitor','taylor@example.test','555-555-0100','I would like to learn more about boarding.',true,'/site/checkin-test','','inquiry-once'),(select id from website_inquiries),'inquiry retry is idempotent');
select is((app.get_tenant_website_readiness((select id from businesses where public_slug='checkin-test'))->>'hero'),'true','readiness reports completed hero');
select lives_ok($$select app.unpublish_tenant_website((select id from businesses where public_slug='checkin-test'))$$,'authorized staff unpublishes site');
select is(app.get_public_tenant_website('checkin-test'),null::jsonb,'unpublished site no longer resolves publicly');
select lives_ok($$select app.transition_website_inquiry((select id from businesses where public_slug='checkin-test'),(select id from website_inquiries),'in_review','Front desk is reviewing the request.','inquiry-review')$$,'staff starts inquiry review');
select lives_ok($$select app.transition_website_inquiry((select id from businesses where public_slug='checkin-test'),(select id from website_inquiries),'responded','Customer received a documented response.','inquiry-response')$$,'staff records inquiry response');
select is((select status from website_inquiries),'responded','inquiry workflow exposes explicit status');
select lives_ok($$select app.request_tenant_custom_domain((select id from businesses where public_slug='checkin-test'),'care.checkin-example.test')$$,'business requests normalized custom domain');
select is((select status from tenant_domain_bindings),'verification_pending','custom domain awaits trusted verification');
select is(left((select verification_token from tenant_domain_bindings),21),'petcare-verification=','custom domain receives DNS ownership token');
select lives_ok($$select app.grant_customer_portal_access((select id from businesses where public_slug='checkin-test'),(select id from customers),'82000000-0000-4000-8000-000000000001')$$,'staff restores portal access for branded experience');
select is((app.get_customer_portal_brand((select id from businesses where public_slug='checkin-test'))->'brand_tokens'->>'primary'),'#23664f','customer portal uses published tenant brand token');
select lives_ok($$select app.get_business_summary_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')$$,'authorized business summary runs');
select is((app.get_business_summary_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->>'definition_version'),'1','report exposes canonical definition version');
select is((app.get_business_summary_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'period'->>'time_basis'),'UTC','report exposes time basis');
select is((app.get_business_summary_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'freshness'->>'status'),'current','report exposes freshness state');
select is((app.get_business_summary_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->>'currency_code'),'USD','report exposes currency without relabeling cash');
select is((app.get_business_summary_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'operational'->>'booking_requests'),'1','booking request count reconciles to source');
select is((app.get_business_summary_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'financial'->>'outstanding_balance_minor')::bigint >= 0,true,'outstanding balance is a nonnegative as-of measure');
select is((select count(*) from reporting_runs),7::bigint,'each successful report run is auditable');
select lives_ok($$select app.get_booking_activity_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days',false)$$,'authorized booking activity report runs');
select is((app.get_booking_activity_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days',false)->>'definition_version'),'1','booking activity exposes definition version');
select is((app.get_booking_activity_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days',false)->>'row_count'),'1','booking activity reconciles one item');
select is((app.get_booking_activity_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days',false)->'rows'->0->>'booking_number'),(select booking_number from bookings),'drill-down preserves source booking number');
select is((app.get_booking_activity_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days',false)->'rows'->0->>'pet_name'),'Milo','drill-down preserves pet identity');
select lives_ok($$select app.get_booking_activity_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days',true)$$,'authorized CSV export projection runs');
select is((select count(*) from report_exports),1::bigint,'export is audited once');
select is((select row_count from report_exports),1,'export audit records row count');
select lives_ok($$select app.get_capacity_utilization_report((select id from businesses where public_slug='checkin-test'),current_date,current_date+3)$$,'authorized utilization report runs');
select is((app.get_capacity_utilization_report((select id from businesses where public_slug='checkin-test'),current_date,current_date+3)->>'definition_version'),'1','utilization exposes definition version');
select is((app.get_capacity_utilization_report((select id from businesses where public_slug='checkin-test'),current_date,current_date+3)->'period'->>'day_basis'),'location_local_time','utilization exposes local-day basis');
select is(jsonb_array_length(app.get_capacity_utilization_report((select id from businesses where public_slug='checkin-test'),current_date,current_date+3)->'rows'),4,'one active pool produces one row per day');
select is((select max((value->>'occupancy_rate_percent')::numeric)<=100 from jsonb_array_elements(app.get_capacity_utilization_report((select id from businesses where public_slug='checkin-test'),current_date,current_date+3)->'rows')),true,'occupancy rate never exceeds one hundred percent');
select is((select max((value->>'occupied_resource_hours')::numeric)>0 from jsonb_array_elements(app.get_capacity_utilization_report((select id from businesses where public_slug='checkin-test'),current_date,current_date+3)->'rows')),true,'committed stay contributes occupied hours');
select lives_ok($$select app.get_financial_reconciliation_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')$$,'authorized financial reconciliation runs');
select is((app.get_financial_reconciliation_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->>'definition_version'),'1','financial reconciliation exposes definition version');
select is((app.get_financial_reconciliation_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'summary'->>'invoice_count'),'1','financial report reconciles one invoice');
select is((app.get_financial_reconciliation_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'rows'->0->>'invoice_number'),(select invoice_number from invoices),'financial detail preserves invoice identity');
select is((app.get_financial_reconciliation_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->>'mixed_currency'),'false','single-currency report is explicit');
select is((app.get_financial_reconciliation_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'summary'->>'outstanding_minor')::bigint>=0,true,'financial outstanding total is nonnegative');
select lives_ok($$select app.get_care_compliance_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')$$,'authorized care compliance report runs');
select is((app.get_care_compliance_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->>'definition_version'),'1','care compliance exposes definition version');
select is((app.get_care_compliance_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'summary'->>'incident_count'),'1','care report reconciles incident count');
select is((app.get_care_compliance_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'summary'->>'report_cards_published'),'1','care report reconciles published report card');
select is((app.get_care_compliance_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'summary'->>'serious_or_critical_incidents'),'1','serious incident guardrail is visible');
select is(jsonb_array_length(app.get_care_compliance_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'task_types')>0,true,'care task types are summarized');
select is((app.get_care_compliance_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'summary'->>'on_time_rate_percent')::numeric between 0 and 100,true,'on-time rate remains bounded');
select lives_ok($$select app.get_customer_service_mix_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')$$,'authorized customer and service report runs');
select is((app.get_customer_service_mix_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->>'definition_version'),'1','customer report exposes definition version');
select is((app.get_customer_service_mix_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'summary'->>'completed_bookings'),'1','customer report reconciles completed booking');
select is((app.get_customer_service_mix_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'summary'->>'first_time_completed_customers'),'1','first completion cohort is explicit');
select is((app.get_customer_service_mix_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'summary'->>'returning_completed_customers'),'0','returning cohort excludes first completion');
select is(jsonb_array_length(app.get_customer_service_mix_report((select id from businesses where public_slug='checkin-test'),now()-interval '30 days',now()+interval '30 days')->'service_mix'),1,'completed service mix preserves one service row');
select is(app.get_platform_context(),null::jsonb,'tenant owner has no implicit platform authority');
set local role service_role;
select lives_ok($$select app.grant_platform_operator('82000000-0000-4000-8000-000000000001','platform_admin','Founder platform administration bootstrap.')$$,'service role grants documented platform assignment');
set local role authenticated;
select is((app.get_platform_context()->'roles'->>0),'platform_admin','platform context exposes assigned role');
select is(app.platform_has_permission('platform.businesses.manage'),true,'platform administrator receives lifecycle permission');
select is(jsonb_array_length(app.list_platform_tenants()),1,'safe platform directory returns tenant metadata');
select lives_ok($$select app.transition_platform_tenant((select id from businesses where public_slug='checkin-test'),'restricted','billing_review','Subscription state requires documented review.','','platform-restrict')$$,'platform administrator restricts tenant');
select is((select lifecycle_status from platform_tenant_controls),'restricted','tenant lifecycle control records restriction');
select lives_ok($$select app.transition_platform_tenant((select id from businesses where public_slug='checkin-test'),'suspended','security_review','Security containment requires temporary suspension.','checkin-test','platform-suspend')$$,'slug-confirmed suspension succeeds');
select is((select status from businesses),'suspended','suspension updates coarse tenant access state');
select is((select count(*) from platform_tenant_events),2::bigint,'platform lifecycle history is immutable and additive');
select is(app.platform_has_permission('platform.subscriptions.manage'),true,'platform administrator receives SaaS subscription permission');
select is(jsonb_array_length(app.list_saas_plans()),1,'active SaaS plan is listed');
select lives_ok($$select app.assign_tenant_saas_subscription((select id from businesses where public_slug='checkin-test'),(select id from saas_plan_versions where status='active'),true,'Design partner trial subscription assignment.','saas-assign')$$,'platform assigns trial subscription');
select is((select status from tenant_saas_subscriptions),'trialing','subscription begins in trial state');
select is((select value from saas_plan_entitlements where entitlement_key='website.custom_domain'),'false'::jsonb,'plan entitlement remains typed JSON');
select lives_ok($$select app.transition_tenant_saas_subscription((select id from businesses where public_slug='checkin-test'),'active','Trial converted after documented approval.','saas-activate')$$,'platform activates subscription');
select is((select status from tenant_saas_subscriptions),'active','subscription reaches active state');
select is((select count(*) from tenant_saas_subscription_events),2::bigint,'subscription history is additive');
select is(jsonb_array_length(app.list_tenant_saas_subscriptions()),1,'tenant subscription directory remains safe and complete');
select is((select count(*) from invoices),1::bigint,'SaaS subscription never creates customer invoice');
select is(app.platform_has_permission('platform.features.manage'),true,'platform administrator receives feature control permission');
select lives_ok($$select app.configure_platform_feature('live.operations','Live operations','Real-time operational command center release.','','enabled',100,'Initial controlled release to eligible tenants.','','feature-live')$$,'release manager creates global feature');
select is(jsonb_array_length(app.list_platform_feature_controls()),1,'feature directory lists release control');
select is((app.evaluate_tenant_feature((select id from businesses where public_slug='checkin-test'),'live.operations')->>'enabled'),'true','fully released feature evaluates enabled');
select lives_ok($$select app.configure_platform_feature('custom.domains','Custom domains','Tenant custom domain capability release.','website.custom_domain','enabled',100,'Release remains subject to purchased entitlement.','','feature-domain')$$,'entitlement-bound feature is created');
select is((app.evaluate_tenant_feature((select id from businesses where public_slug='checkin-test'),'custom.domains')->>'enabled'),'false','release flag cannot bypass false entitlement');
select is((app.evaluate_tenant_feature((select id from businesses where public_slug='checkin-test'),'custom.domains')->>'source'),'entitlement_denied','evaluation explains entitlement denial');
select lives_ok($$select app.set_platform_feature_override((select id from businesses where public_slug='checkin-test'),'live.operations','disabled','Design partner temporarily excluded from rollout.',now()+interval '1 day','feature-override')$$,'tenant override is documented');
select is((app.evaluate_tenant_feature((select id from businesses where public_slug='checkin-test'),'live.operations')->>'enabled'),'false','active tenant override disables release');
select lives_ok($$select app.configure_platform_feature('live.operations','Live operations','Real-time operational command center release.','','kill_switch',100,'Emergency containment while behavior is reviewed.','live.operations','feature-kill')$$,'confirmed kill switch activates');
select is((app.evaluate_tenant_feature((select id from businesses where public_slug='checkin-test'),'live.operations')->>'source'),'kill_switch','kill switch wins over tenant targeting');
select is((select count(*) from platform_feature_events),4::bigint,'feature changes preserve immutable audit history');
select is((select count(*) from invoices),1::bigint,'feature controls never mutate customer commerce');
select is(app.platform_has_permission('platform.support.manage'),true,'platform administrator receives support session permission');
select lives_ok($$select app.open_platform_support_session((select id from businesses where public_slug='checkin-test'),'SUP-1042','Investigate delayed operational dashboard refresh.',array['operations','audit'],false,30,'Review safe operational diagnostics for reported delay.','support-open')$$,'operator opens case-linked support session');
select is((select count(*) from platform_support_cases),1::bigint,'support case is tenant linked');
select is((select status from platform_support_sessions),'active','support session begins active');
select is(app.platform_support_session_allows((select id from businesses where public_slug='checkin-test'),'operations',false),true,'active support scope authorizes read access');
select is(app.platform_support_session_allows((select id from businesses where public_slug='checkin-test'),'operations',true),false,'read-only support session cannot authorize writes');
select is(jsonb_array_length(app.list_platform_support_sessions()),1,'support directory lists safe session metadata');
select lives_ok($$select app.revoke_platform_support_session((select id from platform_support_sessions),'Reported diagnostic review completed.','support-revoke')$$,'operator revokes support access immediately');
select is(app.platform_support_session_allows((select id from businesses where public_slug='checkin-test'),'operations',false),false,'revoked support session no longer authorizes access');
select is((select count(*) from platform_support_session_events),2::bigint,'support session history is immutable and additive');
select is(app.platform_has_permission('platform.jobs.manage'),true,'platform administrator receives safe retry permission');
set local role service_role;
select lives_ok($$select app.register_platform_administrative_job((select id from businesses where public_slug='checkin-test'),'subscription_reconciliation','subscription:test','failed',true,40,'provider_timeout','Provider did not respond before the safe timeout.','job-retryable')$$,'internal worker registers sanitized failed job');
select lives_ok($$select app.register_platform_administrative_job((select id from businesses where public_slug='checkin-test'),'privacy_export','privacy:test','failed',false,20,'manual_review','Export requires privacy-operator review.','job-manual')$$,'internal worker registers nonretryable failure');
set local role authenticated;
select is(jsonb_array_length(app.list_platform_administrative_jobs()),2,'job directory exposes both safe records');
select is((select next_action from platform_administrative_jobs where idempotency_key='job-retryable'),'retry','retryable failure exposes retry action');
select is((select next_action from platform_administrative_jobs where idempotency_key='job-manual'),'investigate','nonretryable failure requires investigation');
select throws_ok($$select app.retry_platform_administrative_job((select id from platform_administrative_jobs where idempotency_key='job-manual'),'Attempt an unsafe retry.','job-unsafe-retry')$$,'P0001','job is not safely retryable','unsafe job retry is rejected');
select lives_ok($$select app.retry_platform_administrative_job((select id from platform_administrative_jobs where idempotency_key='job-retryable'),'Provider recovered; queue idempotent reconciliation.','job-safe-retry')$$,'safe retry is queued');
select is((select status from platform_administrative_jobs where idempotency_key='job-retryable'),'queued','retried job returns to queue');
select is((select attempt_count from platform_administrative_jobs where idempotency_key='job-retryable'),2,'retry increments attempt count');
select is((select count(*) from platform_administrative_job_attempts),3::bigint,'original attempts remain alongside retry request');
select is((select count(*) from invoices),1::bigint,'administrative jobs remain separate from customer commerce');
select is(app.platform_has_permission('platform.privacy.manage'),true,'platform administrator receives privacy coordination permission');
select lives_ok($$select app.create_platform_privacy_request((select id from businesses where public_slug='checkin-test'),'portable_export','customer:checkin-owner','customer_support',now()+interval '30 days',false,'Customer requested a verified portable export.','privacy-create')$$,'privacy request is recorded with minimized reference');
select is((select status from platform_privacy_requests),'received','privacy request begins received');
select throws_ok($$select app.transition_platform_privacy_request((select id from platform_privacy_requests),'fulfilled','Attempt fulfillment before verification.','privacy-too-early')$$,'P0001','controlled privacy transition required','unverified request cannot be fulfilled');
select lives_ok($$select app.transition_platform_privacy_request((select id from platform_privacy_requests),'identity_verified','Identity verification evidence was reviewed.','privacy-verified')$$,'identity verification is explicit');
select lives_ok($$select app.record_platform_privacy_domain_action((select id from platform_privacy_requests),'customer','export','completed','Customer export artifact generated and reviewed.','','Customer domain completed approved export.','privacy-customer')$$,'domain action records minimized evidence');
select lives_ok($$select app.transition_platform_privacy_request((select id from platform_privacy_requests),'in_progress','Verified request assigned to domain owners.','privacy-progress')$$,'verified request enters fulfillment');
select lives_ok($$select app.transition_platform_privacy_request((select id from platform_privacy_requests),'review','All assigned domain actions are ready for review.','privacy-review')$$,'request enters final review');
select lives_ok($$select app.transition_platform_privacy_request((select id from platform_privacy_requests),'fulfilled','Privacy operator approved completed export evidence.','privacy-fulfilled')$$,'completed domain work permits fulfillment');
select is((select status from platform_privacy_requests),'fulfilled','privacy request reaches fulfilled');
select is(jsonb_array_length(app.list_platform_privacy_requests()),1,'privacy directory returns request and actions');
select is((select count(*) from platform_privacy_events),6::bigint,'privacy history is immutable and additive');
select is((select count(*) from invoices),1::bigint,'privacy coordination never changes customer commerce');
select is(app.platform_has_permission('platform.health.manage'),true,'platform administrator receives health issue permission');
select lives_ok($$select app.create_platform_operational_issue((select id from businesses where public_slug='checkin-test'),'provider:test:latency','provider','provider-incident-42','critical','Provider latency affects operational refresh.','One test tenant sees delayed non-safety-critical dashboard refresh.','Founder correlated provider and tenant evidence.','health-create')$$,'founder records sanitized correlated issue');
select is((app.get_platform_health_summary()->>'open_critical_issues'),'1','health summary counts critical issue');
select is((app.get_platform_health_summary()->'tenants'->>'suspended'),'1','health summary counts suspended tenant');
select is(jsonb_array_length(app.list_platform_operational_issues()),1,'issue directory exposes correlated issue');
select lives_ok($$select app.transition_platform_operational_issue((select id from platform_operational_issues),'monitoring','Provider recovery observed; continue monitoring.','health-monitor')$$,'issue moves to monitoring');
select lives_ok($$select app.transition_platform_operational_issue((select id from platform_operational_issues),'resolved','Provider recovery confirmed and tenant impact ended.','health-resolve')$$,'issue resolves with evidence');
select is((app.get_platform_health_summary()->>'open_critical_issues'),'0','resolved issue leaves active critical count');
select is((select count(*) from platform_operational_issue_events),3::bigint,'issue history remains immutable and additive');
select is(jsonb_array_length(app.search_platform_audit_events((select id from businesses where public_slug='checkin-test'),null,'health.',null,null,null,100)),3,'audit search filters correlated health events');
select is(jsonb_array_length(app.search_platform_audit_events(null,null,'support.','SUP-1042',null,null,100)),2,'audit search filters by support case');
select is((select count(*) from invoices),1::bigint,'health and audit projections never mutate tenant commerce');
select is((select count(*) from customers),1::bigint,'platform health never exposes or mutates customer records');
select is(app.platform_has_permission('platform.provisioning.manage'),true,'platform administrator receives provisioning recovery permission');
set local role service_role;
select lives_ok($$select app.register_tenant_provisioning_run((select id from businesses where public_slug='checkin-test'),'provisioning-checkin-test')$$,'worker registers resumable provisioning run');
select lives_ok($$select app.record_tenant_provisioning_step((select id from tenant_provisioning_runs),'reserve_tenant','completed','','',true,'provision-reserved')$$,'first provisioning step completes');
select lives_ok($$select app.record_tenant_provisioning_step((select id from tenant_provisioning_runs),'owner_membership','failed','identity_provider_timeout','Identity provider did not respond before safe timeout.',true,'provision-owner-failed')$$,'worker records sanitized retryable failure');
set local role authenticated;
select is((select status from tenant_provisioning_runs),'failed','provisioning run exposes failed state');
select is((select current_step_key from tenant_provisioning_runs),'owner_membership','failed step remains explicit');
select is(jsonb_array_length(app.list_tenant_provisioning_runs()),1,'provisioning directory returns ordered run');
select lives_ok($$select app.retry_tenant_provisioning_step((select id from tenant_provisioning_runs),'Identity provider recovered; retry owner membership.','provision-owner-retry')$$,'operator safely retries failed step');
select is((select status from tenant_provisioning_runs),'running','retry resumes provisioning run');
select is((select status from tenant_provisioning_steps where step_key='owner_membership'),'running','retry resumes only failed step');
select is((select count(*) from tenant_provisioning_events),4::bigint,'provisioning history remains immutable and additive');
select * from finish();rollback;
