begin;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions;select plan(30);
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,email_change_token_new,recovery_token) values('00000000-0000-0000-0000-000000000000','82000000-0000-4000-8000-000000000001','authenticated','authenticated','checkin-owner@example.test','',now(),'{}','{"display_name":"Check-in Owner"}',now(),now(),'','','','');
set local role authenticated;select set_config('request.jwt.claims','{"sub":"82000000-0000-4000-8000-000000000001","role":"authenticated","email":"checkin-owner@example.test","aal":"aal2"}',true);
select lives_ok($$select * from app.create_business_with_owner('Check-in Test','checkin-test','Main','main','America/Chicago')$$,'tenant created');
select lives_ok($$select app.create_customer_household_with_pet((select id from businesses where public_slug='checkin-test'),'Pat','Owner','','checkin@example.test',null,'Milo','Mixed breed','2020-01-01',false,'male')$$,'customer and pet created');
select lives_ok($$select app.create_service_draft((select id from businesses where public_slug='checkin-test'),'boarding','Boarding','Boarding','overnight_date_range',null,'staff_approval','Stay')$$,'service created');
select lives_ok($$select app.publish_service_version((select business_id from services),(select id from services),(select id from service_versions),(select id from locations),false,true,true,false)$$,'service published');
select lives_ok($$select app.configure_capacity_pool((select business_id from services),(select id from locations),(select id from services),'Capacity','count',2,2)$$,'capacity configured');
select lives_ok($$select * from app.create_pricing_bundle((select id from businesses where public_slug='checkin-test'),(select id from locations),'USD','USD','Deposit','percentage',5000,0,24,5000,10000,'Agreement','Accepted payment terms.','Half deposit.')$$,'pricing configured');
select lives_ok($$select app.add_price_rate((select business_id from price_books),(select id from price_book_versions),(select id from locations),(select id from service_versions),'night',10000,'Night',100,null,null)$$,'rate created');
select lives_ok($$select app.publish_pricing_bundle((select business_id from price_books),(select id from price_book_versions),(select id from commercial_policy_versions),current_date)$$,'pricing published');
select lives_ok($$select app.create_booking_request((select business_id from services),(select id from locations),(select id from customers),(select id from pets),(select id from services),now()+interval '2 days',now()+interval '4 days',1,2,null,'staff','checkin-booking')$$,'booking requested');
select lives_ok($$select app.resolve_booking_review((select business_id from bookings),(select id from bookings),'approved','Manager approved check-in test','checkin-approval')$$,'booking approved');
select lives_ok($$select app.issue_booking_invoice((select business_id from bookings),(select id from bookings),'checkin-invoice')$$,'invoice issued');
select lives_ok($$select app.record_manual_payment((select business_id from invoices),(select id from invoices),(select location_id from invoices),10000,'check','CHECK-IN','checkin-deposit')$$,'deposit posted');
select is((select status from bookings),'confirmed','deposit confirms booking');
select lives_ok($$select app.record_booking_arrival((select business_id from bookings),(select id from bookings),'arrival-once')$$,'arrival recorded');
select is(app.record_booking_arrival((select business_id from bookings),(select id from bookings),'arrival-retry'),(select id from operational_visits),'arrival retry returns same visit');
select is((select count(*) from operational_visits),1::bigint,'one operational visit created');
select is((select status from operational_visits),'arrived','arrival remains distinct from check-in');
select is((select status from pet_visits),'arrived','pet is physically arrived');
select lives_ok($$select app.complete_pet_check_in((select business_id from bookings),(select id from bookings),(select id from pets),'Pat Owner','owner','photo_id','["name:Milo","breed:Mixed breed"]','{"notes":"No visible concerns"}','[{"category":"belonging","name":"Blue leash","quantity":1,"unit":"item","storage":"Cubby A","return_expected":true}]','checkin-once')$$,'custody accepted');
select is(app.complete_pet_check_in((select business_id from bookings),(select id from bookings),(select id from pets),'Pat Owner','owner','photo_id','["name:Milo","breed:Mixed breed"]','{"notes":"No visible concerns"}','[]','checkin-once'),(select id from check_in_records),'check-in retry returns same record');
select is((select status from operational_visits),'in_care','visit enters care after all pets check in');
select is((select status from pet_visits),'in_care','pet enters care');
select is((select count(*) from check_in_records),1::bigint,'one immutable check-in record retained');
select is((select count(*) from care_plan_snapshots),1::bigint,'one care snapshot retained');
select is((select count(*) from visit_custody_items),1::bigint,'custody item is not duplicated');
select is((select count(*) from operational_timeline_events),2::bigint,'arrival and check-in timeline events retained');
select is((select jsonb_array_length(verified_identifiers) from check_in_records),2,'two pet identifiers preserved');
select is((select jsonb_typeof(snapshot->'medications') from care_plan_snapshots),'array','care snapshot has structured medication data');
select throws_ok($$update care_plan_snapshots set snapshot='{}'$$,'P0001','commercial snapshots are immutable','care snapshot cannot be rewritten');
select throws_ok($$select app.complete_pet_check_in((select business_id from bookings),(select id from bookings),(select id from pets),'Pat Owner','owner','photo_id','["name:Milo","name:Milo"]','{}','[]','different-key')$$,'22023','two pet identifiers are required','duplicate identity signals are rejected');
select * from finish();rollback;
