-- PetCare E12 governed tenant website drafts, publication, and rollback.
create table public.tenant_websites(
 id uuid primary key default gen_random_uuid(),business_id uuid not null unique,status text not null default 'draft' check(status in('draft','published','unpublished','archived')),theme_key text not null default 'modern' check(theme_key in('modern','warm','classic')),
 brand_tokens jsonb not null default '{"primary":"#23664f","accent":"#d97745"}'::jsonb check(jsonb_typeof(brand_tokens)='object'),draft_content jsonb not null default '{}'::jsonb check(jsonb_typeof(draft_content)='object'),current_publication_number integer not null default 0 check(current_publication_number>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(business_id,id),foreign key(business_id) references public.businesses(id) on delete restrict
);
create table public.tenant_website_publications(
 id uuid primary key default gen_random_uuid(),business_id uuid not null,tenant_website_id uuid not null,publication_number integer not null,theme_key text not null,brand_tokens jsonb not null,content_snapshot jsonb not null,seo_snapshot jsonb not null,
 published_by uuid not null references auth.users(id) on delete restrict default auth.uid(),published_at timestamptz not null default now(),source_publication_id uuid,unique(business_id,id),unique(business_id,tenant_website_id,publication_number),foreign key(business_id,tenant_website_id) references public.tenant_websites(business_id,id) on delete restrict,foreign key(source_publication_id) references public.tenant_website_publications(id) on delete restrict
);
create trigger tenant_websites_updated before update on public.tenant_websites for each row execute function app.set_updated_at();create trigger tenant_websites_tenant before update on public.tenant_websites for each row execute function app.prevent_business_id_change();create trigger tenant_websites_audit after insert or update or delete on public.tenant_websites for each row execute function app.audit_configuration_change('website.changed','tenant_website');create trigger tenant_website_publications_immutable before update or delete on public.tenant_website_publications for each row execute function app.prevent_commercial_snapshot_change();

create or replace function app.save_tenant_website_draft(target_business_id uuid,theme_value text,brand_value jsonb,content_value jsonb)
returns uuid language plpgsql security definer set search_path='' as $$declare site_id uuid;begin if not app.member_has_permission(target_business_id,'website.edit') then raise exception 'website editing unavailable' using errcode='42501';end if;if theme_value not in('modern','warm','classic') or jsonb_typeof(brand_value)<>'object' or jsonb_typeof(content_value)<>'object' or coalesce(brand_value->>'primary','')!~'^#[0-9A-Fa-f]{6}$' or coalesce(brand_value->>'accent','')!~'^#[0-9A-Fa-f]{6}$' then raise exception 'valid governed website content required' using errcode='22023';end if;insert into public.tenant_websites(business_id,theme_key,brand_tokens,draft_content) values(target_business_id,theme_value,brand_value,content_value) on conflict(business_id) do update set theme_key=excluded.theme_key,brand_tokens=excluded.brand_tokens,draft_content=excluded.draft_content,status=case when public.tenant_websites.status='published' then 'published' else 'draft' end returning id into site_id;return site_id;end;$$;

create or replace function app.publish_tenant_website(target_business_id uuid,source_publication_value uuid default null)
returns uuid language plpgsql security definer set search_path='' as $$declare site public.tenant_websites%rowtype;publication_id uuid;snapshot jsonb;next_number integer;begin if not app.member_has_permission(target_business_id,'website.publish') then raise exception 'website publishing unavailable' using errcode='42501';end if;select * into site from public.tenant_websites where business_id=target_business_id for update;if site.id is null then raise exception 'website draft unavailable' using errcode='P0002';end if;if source_publication_value is null then snapshot:=site.draft_content;else select content_snapshot into snapshot from public.tenant_website_publications where business_id=target_business_id and id=source_publication_value;if snapshot is null then raise exception 'publication unavailable' using errcode='P0002';end if;end if;if char_length(trim(coalesce(snapshot->>'hero_title','')))<5 or char_length(trim(coalesce(snapshot->>'hero_body','')))<12 or char_length(trim(coalesce(snapshot->>'about','')))<12 or jsonb_typeof(snapshot->'faqs')<>'array' or jsonb_array_length(snapshot->'faqs')<1 or char_length(trim(coalesce(snapshot->>'contact_email','')))<3 then raise exception 'website readiness checks failed' using errcode='22023';end if;next_number:=site.current_publication_number+1;insert into public.tenant_website_publications(business_id,tenant_website_id,publication_number,theme_key,brand_tokens,content_snapshot,seo_snapshot,source_publication_id) values(target_business_id,site.id,next_number,site.theme_key,site.brand_tokens,snapshot,jsonb_build_object('title',coalesce(snapshot->>'seo_title',snapshot->>'hero_title'),'description',coalesce(snapshot->>'seo_description',snapshot->>'hero_body')),source_publication_value) returning id into publication_id;update public.tenant_websites set status='published',current_publication_number=next_number where id=site.id;return publication_id;end;$$;

create or replace function app.get_public_tenant_website(public_slug_value text)
returns jsonb language sql security definer stable set search_path='' as $$select jsonb_build_object('business',jsonb_build_object('name',b.name,'slug',b.public_slug),'theme_key',p.theme_key,'brand_tokens',p.brand_tokens,'content',p.content_snapshot,'seo',p.seo_snapshot,'services',coalesce((select jsonb_agg(jsonb_build_object('name',sv.customer_name,'description',sv.short_description,'category',s.category) order by s.display_order) from public.services s join public.service_versions sv on sv.business_id=s.business_id and sv.service_id=s.id and sv.status='published' where s.business_id=b.id and s.status='active' and exists(select 1 from public.service_location_enablements e where e.business_id=s.business_id and e.service_id=s.id and e.enabled and e.public_website)),'[]'::jsonb),'locations',coalesce((select jsonb_agg(jsonb_build_object('name',l.name,'time_zone',l.time_zone) order by l.name) from public.locations l where l.business_id=b.id and l.status='active'),'[]'::jsonb)) from public.businesses b join public.tenant_websites w on w.business_id=b.id and w.status='published' join public.tenant_website_publications p on p.business_id=w.business_id and p.tenant_website_id=w.id and p.publication_number=w.current_publication_number where b.public_slug=lower(trim(public_slug_value)) and b.status='active'$$;

alter table public.tenant_websites enable row level security;alter table public.tenant_websites force row level security;alter table public.tenant_website_publications enable row level security;alter table public.tenant_website_publications force row level security;revoke all on public.tenant_websites,public.tenant_website_publications from anon,authenticated;grant select on public.tenant_websites,public.tenant_website_publications to authenticated;create policy tenant_websites_staff on public.tenant_websites for select to authenticated using(app.member_has_permission(business_id,'website.edit'));create policy tenant_website_publications_staff on public.tenant_website_publications for select to authenticated using(app.member_has_permission(business_id,'website.edit'));
revoke all on function app.save_tenant_website_draft(uuid,text,jsonb,jsonb),app.publish_tenant_website(uuid,uuid),app.get_public_tenant_website(text) from public;grant execute on function app.save_tenant_website_draft(uuid,text,jsonb,jsonb),app.publish_tenant_website(uuid,uuid) to authenticated;grant execute on function app.get_public_tenant_website(text) to anon,authenticated;
