-- PetCare E14 completion: break-glass review, plan governance, expiring overrides, and authorized purge evidence.
alter table public.platform_permission_definitions drop constraint platform_permission_definitions_permission_key_check;
alter table public.platform_permission_definitions add constraint platform_permission_definitions_permission_key_check check(permission_key in(
 'platform.businesses.read','platform.businesses.manage','platform.audit.read','platform.audit.export','platform.subscriptions.read','platform.subscriptions.manage',
 'platform.features.read','platform.features.manage','platform.support.read','platform.support.manage','platform.support.write','platform.jobs.read','platform.jobs.manage',
 'platform.privacy.read','platform.privacy.manage','platform.health.read','platform.health.manage','platform.provisioning.read','platform.provisioning.manage',
 'platform.communications.read','platform.communications.manage','platform.notes.read','platform.notes.manage','platform.closure.read','platform.closure.manage',
 'platform.break_glass.read','platform.break_glass.manage','platform.purge.read','platform.purge.manage'
));
insert into public.platform_permission_definitions(permission_key,description) values
('platform.break_glass.read','Review emergency tenant access and mandatory post-use review.'),('platform.break_glass.manage','Activate and review narrowly scoped emergency access.'),
('platform.purge.read','View minimized purge authorization and execution evidence.'),('platform.purge.manage','Request and separately authorize eligible tenant purge jobs.');
insert into public.platform_role_permissions(role_key,permission_key) values
('platform_admin','platform.break_glass.read'),('platform_admin','platform.break_glass.manage'),('platform_admin','platform.purge.read'),('platform_admin','platform.purge.manage'),
('platform_support','platform.break_glass.read'),('platform_auditor','platform.break_glass.read'),('platform_auditor','platform.purge.read');

create table public.platform_break_glass_sessions(
 id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete restrict,operator_id uuid not null references public.identity_profiles(id) on delete restrict,
 incident_key text not null check(incident_key~'^[A-Z][A-Z0-9-]{5,39}$'),scopes text[] not null check(cardinality(scopes) between 1 and 3 and scopes<@array['operations','security','audit']::text[]),
 reason text not null check(char_length(trim(reason)) between 20 and 500),status text not null default 'active' check(status in('active','ended','reviewed')),
 started_at timestamptz not null default now(),expires_at timestamptz not null,ended_at timestamptz,review_due_at timestamptz not null,reviewed_at timestamptz,reviewed_by uuid references public.identity_profiles(id) on delete restrict,review_outcome text,
 check(expires_at>started_at and expires_at<=started_at+interval '15 minutes'),check(review_due_at<=started_at+interval '24 hours')
);
create table public.platform_break_glass_events(id uuid primary key default gen_random_uuid(),platform_break_glass_session_id uuid not null references public.platform_break_glass_sessions(id) on delete restrict,business_id uuid not null references public.businesses(id) on delete restrict,event_type text not null check(event_type in('activated','security_alerted','ended','reviewed')),reason text not null,actor_id uuid not null references public.identity_profiles(id) on delete restrict,occurred_at timestamptz not null default now(),idempotency_key text not null unique);
create trigger break_glass_events_immutable before update or delete on public.platform_break_glass_events for each row execute function app.prevent_commercial_snapshot_change();
create or replace function app.activate_platform_break_glass(target_business_id uuid,incident_key_value text,scopes_value text[],reason_value text,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare session_id uuid;begin if not app.platform_has_permission('platform.break_glass.manage') then raise exception 'break-glass unavailable' using errcode='42501';end if;select platform_break_glass_session_id into session_id from public.platform_break_glass_events where idempotency_key=trim(request_key);if session_id is not null then return session_id;end if;if not exists(select 1 from public.businesses where id=target_business_id) or trim(incident_key_value)!~'^[A-Z][A-Z0-9-]{5,39}$' or cardinality(scopes_value) not between 1 and 3 or not scopes_value<@array['operations','security','audit']::text[] or char_length(trim(coalesce(reason_value,'')))<20 then raise exception 'documented incident-scoped break-glass required' using errcode='22023';end if;insert into public.platform_break_glass_sessions(business_id,operator_id,incident_key,scopes,reason,expires_at,review_due_at) values(target_business_id,auth.uid(),upper(trim(incident_key_value)),scopes_value,trim(reason_value),now()+interval '15 minutes',now()+interval '24 hours') returning id into session_id;insert into public.platform_break_glass_events(platform_break_glass_session_id,business_id,event_type,reason,actor_id,idempotency_key) values(session_id,target_business_id,'activated',trim(reason_value),auth.uid(),trim(request_key)),(session_id,target_business_id,'security_alerted','Security review notification queued.',auth.uid(),trim(request_key)||':alert');return session_id;end;$$;
create or replace function app.end_platform_break_glass(session_id_value uuid,reason_value text,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare s public.platform_break_glass_sessions%rowtype;e uuid;begin if not app.platform_has_permission('platform.break_glass.manage') then raise exception 'break-glass unavailable' using errcode='42501';end if;select id into e from public.platform_break_glass_events where idempotency_key=trim(request_key);if e is not null then return e;end if;select * into s from public.platform_break_glass_sessions where id=session_id_value for update;if s.id is null or s.status<>'active' or char_length(trim(coalesce(reason_value,'')))<12 then raise exception 'active break-glass session required' using errcode='P0001';end if;update public.platform_break_glass_sessions set status='ended',ended_at=now() where id=s.id;insert into public.platform_break_glass_events(platform_break_glass_session_id,business_id,event_type,reason,actor_id,idempotency_key) values(s.id,s.business_id,'ended',trim(reason_value),auth.uid(),trim(request_key)) returning id into e;return e;end;$$;
create or replace function app.review_platform_break_glass(session_id_value uuid,outcome_value text,reason_value text,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare s public.platform_break_glass_sessions%rowtype;e uuid;begin if not app.platform_has_permission('platform.break_glass.manage') then raise exception 'break-glass review unavailable' using errcode='42501';end if;select id into e from public.platform_break_glass_events where idempotency_key=trim(request_key);if e is not null then return e;end if;select * into s from public.platform_break_glass_sessions where id=session_id_value for update;if s.id is null or s.status<>'ended' or outcome_value not in('appropriate','policy_exception','investigation_required') or char_length(trim(coalesce(reason_value,'')))<12 then raise exception 'ended break-glass session review required' using errcode='P0001';end if;update public.platform_break_glass_sessions set status='reviewed',reviewed_at=now(),reviewed_by=auth.uid(),review_outcome=outcome_value where id=s.id;insert into public.platform_break_glass_events(platform_break_glass_session_id,business_id,event_type,reason,actor_id,idempotency_key) values(s.id,s.business_id,'reviewed',trim(reason_value),auth.uid(),trim(request_key)) returning id into e;return e;end;$$;

create table public.tenant_saas_plan_change_requests(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete restrict,tenant_subscription_id uuid not null references public.tenant_saas_subscriptions(id) on delete restrict,from_plan_version_id uuid not null references public.saas_plan_versions(id) on delete restrict,to_plan_version_id uuid not null references public.saas_plan_versions(id) on delete restrict,effective_timing text not null check(effective_timing in('immediate','period_end')),preview jsonb not null,preview_fingerprint text not null check(preview_fingerprint~'^[a-f0-9]{32}$'),status text not null default 'previewed' check(status in('previewed','applied','cancelled')),reason text not null,requested_by uuid not null references public.identity_profiles(id) on delete restrict,created_at timestamptz not null default now(),applied_at timestamptz);
create table public.tenant_entitlement_overrides(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete restrict,entitlement_key text not null,value jsonb not null,starts_at timestamptz not null,expires_at timestamptz not null,reason text not null check(char_length(trim(reason)) between 12 and 500),approved_by uuid not null references public.identity_profiles(id) on delete restrict,created_at timestamptz not null default now(),check(expires_at>starts_at and expires_at<=starts_at+interval '90 days'));
create or replace function app.preview_tenant_saas_plan_change(target_business_id uuid,target_plan_version_id uuid,effective_timing_value text,reason_value text) returns uuid language plpgsql security definer set search_path='' as $$declare s public.tenant_saas_subscriptions%rowtype;from_v public.saas_plan_versions%rowtype;to_v public.saas_plan_versions%rowtype;p jsonb;f text;r uuid;begin if not app.platform_has_permission('platform.subscriptions.manage') then raise exception 'plan change unavailable' using errcode='42501';end if;select * into s from public.tenant_saas_subscriptions where business_id=target_business_id;select * into from_v from public.saas_plan_versions where id=s.saas_plan_version_id;select * into to_v from public.saas_plan_versions where id=target_plan_version_id and status='active';if s.id is null or to_v.id is null or to_v.id=from_v.id or effective_timing_value not in('immediate','period_end') or char_length(trim(coalesce(reason_value,'')))<12 then raise exception 'valid plan change preview required' using errcode='22023';end if;p:=jsonb_build_object('from_amount_minor',from_v.unit_amount_minor,'to_amount_minor',to_v.unit_amount_minor,'currency_code',to_v.currency_code,'from_interval',from_v.billing_interval,'to_interval',to_v.billing_interval,'effective_at',case when effective_timing_value='period_end' then s.current_period_end else now() end,'from_entitlements',(select jsonb_object_agg(entitlement_key,value) from public.saas_plan_entitlements where saas_plan_version_id=from_v.id),'to_entitlements',(select jsonb_object_agg(entitlement_key,value) from public.saas_plan_entitlements where saas_plan_version_id=to_v.id));f:=md5(s.id||':'||from_v.id||':'||to_v.id||':'||effective_timing_value||':'||p::text);insert into public.tenant_saas_plan_change_requests(business_id,tenant_subscription_id,from_plan_version_id,to_plan_version_id,effective_timing,preview,preview_fingerprint,reason,requested_by) values(target_business_id,s.id,from_v.id,to_v.id,effective_timing_value,p,f,trim(reason_value),auth.uid()) returning id into r;return r;end;$$;
create or replace function app.apply_tenant_saas_plan_change(change_request_id_value uuid,preview_fingerprint_value text,confirmation_value text,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare r public.tenant_saas_plan_change_requests%rowtype;s public.tenant_saas_subscriptions%rowtype;b public.businesses%rowtype;e uuid;begin if not app.platform_has_permission('platform.subscriptions.manage') then raise exception 'plan change unavailable' using errcode='42501';end if;select id into e from public.tenant_saas_subscription_events where idempotency_key=trim(request_key);if e is not null then return e;end if;select * into r from public.tenant_saas_plan_change_requests where id=change_request_id_value for update;select * into s from public.tenant_saas_subscriptions where id=r.tenant_subscription_id for update;select * into b from public.businesses where id=r.business_id;if r.id is null or r.status<>'previewed' or s.saas_plan_version_id<>r.from_plan_version_id or r.preview_fingerprint<>preview_fingerprint_value or lower(trim(confirmation_value))<>b.public_slug then raise exception 'current confirmed plan preview required' using errcode='P0001';end if;update public.tenant_saas_subscriptions set saas_plan_version_id=r.to_plan_version_id,changed_by=auth.uid() where id=s.id;update public.tenant_saas_plan_change_requests set status='applied',applied_at=now() where id=r.id;insert into public.tenant_saas_subscription_events(business_id,tenant_subscription_id,event_type,from_status,to_status,reason,actor_id,idempotency_key) values(r.business_id,s.id,'plan_changed',s.status,s.status,r.reason,auth.uid(),trim(request_key)) returning id into e;return e;end;$$;
create or replace function app.grant_tenant_entitlement_override(target_business_id uuid,entitlement_key_value text,value_value jsonb,starts_at_value timestamptz,expires_at_value timestamptz,reason_value text) returns uuid language plpgsql security definer set search_path='' as $$declare r uuid;begin if not app.platform_has_permission('platform.subscriptions.manage') then raise exception 'entitlement override unavailable' using errcode='42501';end if;if not exists(select 1 from public.tenant_saas_subscriptions where business_id=target_business_id) or entitlement_key_value!~'^[a-z][a-z0-9_.]*$' or expires_at_value<=greatest(starts_at_value,now()) or expires_at_value>starts_at_value+interval '90 days' or char_length(trim(coalesce(reason_value,'')))<12 then raise exception 'bounded approved entitlement override required' using errcode='22023';end if;insert into public.tenant_entitlement_overrides(business_id,entitlement_key,value,starts_at,expires_at,reason,approved_by) values(target_business_id,entitlement_key_value,value_value,starts_at_value,expires_at_value,trim(reason_value),auth.uid()) returning id into r;return r;end;$$;

create table public.tenant_purge_requests(id uuid primary key default gen_random_uuid(),tenant_closure_case_id uuid not null unique references public.tenant_closure_cases(id) on delete restrict,business_id uuid not null references public.businesses(id) on delete restrict,status text not null default 'requested' check(status in('requested','approved','executing','completed','failed')),readiness_fingerprint text not null,reason text not null,requested_by uuid not null references public.identity_profiles(id) on delete restrict,requested_at timestamptz not null default now(),approved_by uuid references public.identity_profiles(id) on delete restrict,approved_at timestamptz,completed_at timestamptz,evidence jsonb);
create table public.tenant_purge_events(id uuid primary key default gen_random_uuid(),tenant_purge_request_id uuid not null references public.tenant_purge_requests(id) on delete restrict,event_type text not null check(event_type in('requested','approved','executing','completed','failed')),reason text not null,actor_id uuid references public.identity_profiles(id) on delete restrict,occurred_at timestamptz not null default now(),idempotency_key text not null unique);
create trigger tenant_purge_events_immutable before update or delete on public.tenant_purge_events for each row execute function app.prevent_commercial_snapshot_change();
create or replace function app.request_tenant_purge(closure_case_id_value uuid,readiness_fingerprint_value text,reason_value text,confirmation_value text,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare c public.tenant_closure_cases%rowtype;b public.businesses%rowtype;r jsonb;p uuid;begin if not app.platform_has_permission('platform.purge.manage') then raise exception 'tenant purge unavailable' using errcode='42501';end if;select tenant_purge_request_id into p from public.tenant_purge_events where idempotency_key=trim(request_key);if p is not null then return p;end if;select * into c from public.tenant_closure_cases where id=closure_case_id_value;select * into b from public.businesses where id=c.business_id;r:=app.tenant_closure_readiness(c.business_id);if c.status<>'purge_eligible' or not (r->>'purge_permitted')::boolean or r->>'fingerprint'<>readiness_fingerprint_value or lower(trim(confirmation_value))<>b.public_slug or char_length(trim(coalesce(reason_value,'')))<20 then raise exception 'eligible confirmed purge request required' using errcode='P0001';end if;insert into public.tenant_purge_requests(tenant_closure_case_id,business_id,readiness_fingerprint,reason,requested_by) values(c.id,c.business_id,readiness_fingerprint_value,trim(reason_value),auth.uid()) returning id into p;insert into public.tenant_purge_events(tenant_purge_request_id,event_type,reason,actor_id,idempotency_key) values(p,'requested',trim(reason_value),auth.uid(),trim(request_key));return p;end;$$;
create or replace function app.approve_tenant_purge(purge_request_id_value uuid,confirmation_value text,reason_value text,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare p public.tenant_purge_requests%rowtype;b public.businesses%rowtype;e uuid;begin if not app.platform_has_permission('platform.purge.manage') then raise exception 'tenant purge unavailable' using errcode='42501';end if;select id into e from public.tenant_purge_events where idempotency_key=trim(request_key);if e is not null then return e;end if;select * into p from public.tenant_purge_requests where id=purge_request_id_value for update;select * into b from public.businesses where id=p.business_id;if p.status<>'requested' or lower(trim(confirmation_value))<>b.public_slug or char_length(trim(coalesce(reason_value,'')))<20 then raise exception 'separate explicit purge approval required' using errcode='P0001';end if;update public.tenant_purge_requests set status='approved',approved_by=auth.uid(),approved_at=now() where id=p.id;insert into public.tenant_purge_events(tenant_purge_request_id,event_type,reason,actor_id,idempotency_key) values(p.id,'approved',trim(reason_value),auth.uid(),trim(request_key)) returning id into e;return e;end;$$;
create or replace function app.complete_tenant_purge(purge_request_id_value uuid,evidence_value jsonb,success_value boolean,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare p public.tenant_purge_requests%rowtype;e uuid;kind text;begin select id into e from public.tenant_purge_events where idempotency_key=trim(request_key);if e is not null then return e;end if;select * into p from public.tenant_purge_requests where id=purge_request_id_value for update;if p.status<>'approved' or jsonb_typeof(evidence_value)<>'object' or evidence_value ?| array['customer_data','pet_data','raw_rows'] then raise exception 'minimized purge completion evidence required' using errcode='P0001';end if;kind:=case when success_value then 'completed' else 'failed' end;update public.tenant_purge_requests set status=kind,completed_at=now(),evidence=evidence_value where id=p.id;insert into public.tenant_purge_events(tenant_purge_request_id,event_type,reason,idempotency_key) values(p.id,kind,case when success_value then 'Purge worker completed with minimized evidence.' else 'Purge worker reported failure.' end,trim(request_key)) returning id into e;return e;end;$$;

do $$declare n text;begin foreach n in array array['platform_break_glass_sessions','platform_break_glass_events','tenant_saas_plan_change_requests','tenant_entitlement_overrides','tenant_purge_requests','tenant_purge_events'] loop execute format('alter table public.%I enable row level security',n);execute format('alter table public.%I force row level security',n);execute format('revoke all on public.%I from anon,authenticated',n);end loop;end$$;
grant select on public.platform_break_glass_sessions,public.platform_break_glass_events,public.tenant_saas_plan_change_requests,public.tenant_entitlement_overrides,public.tenant_purge_requests,public.tenant_purge_events to authenticated;
create policy break_glass_sessions_read on public.platform_break_glass_sessions for select to authenticated using(app.platform_has_permission('platform.break_glass.read'));create policy break_glass_events_read on public.platform_break_glass_events for select to authenticated using(app.platform_has_permission('platform.audit.read'));create policy plan_changes_read on public.tenant_saas_plan_change_requests for select to authenticated using(app.platform_has_permission('platform.subscriptions.read'));create policy entitlement_overrides_read on public.tenant_entitlement_overrides for select to authenticated using(app.platform_has_permission('platform.subscriptions.read'));create policy purge_requests_read on public.tenant_purge_requests for select to authenticated using(app.platform_has_permission('platform.purge.read'));create policy purge_events_read on public.tenant_purge_events for select to authenticated using(app.platform_has_permission('platform.audit.read'));
revoke all on function app.activate_platform_break_glass(uuid,text,text[],text,text),app.end_platform_break_glass(uuid,text,text),app.review_platform_break_glass(uuid,text,text,text),app.preview_tenant_saas_plan_change(uuid,uuid,text,text),app.apply_tenant_saas_plan_change(uuid,text,text,text),app.grant_tenant_entitlement_override(uuid,text,jsonb,timestamptz,timestamptz,text),app.request_tenant_purge(uuid,text,text,text,text),app.approve_tenant_purge(uuid,text,text,text),app.complete_tenant_purge(uuid,jsonb,boolean,text) from public;
grant execute on function app.activate_platform_break_glass(uuid,text,text[],text,text),app.end_platform_break_glass(uuid,text,text),app.review_platform_break_glass(uuid,text,text,text),app.preview_tenant_saas_plan_change(uuid,uuid,text,text),app.apply_tenant_saas_plan_change(uuid,text,text,text),app.grant_tenant_entitlement_override(uuid,text,jsonb,timestamptz,timestamptz,text),app.request_tenant_purge(uuid,text,text,text,text),app.approve_tenant_purge(uuid,text,text,text) to authenticated;grant execute on function app.complete_tenant_purge(uuid,jsonb,boolean,text) to service_role;

alter table public.tenant_saas_subscriptions add column scheduled_saas_plan_version_id uuid references public.saas_plan_versions(id) on delete restrict,add column scheduled_plan_effective_at timestamptz;
alter table public.platform_break_glass_sessions add constraint platform_break_glass_review_window_check check(review_due_at>started_at and review_due_at<=started_at+interval '24 hours');

create or replace function app.apply_tenant_saas_plan_change(change_request_id_value uuid,preview_fingerprint_value text,confirmation_value text,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare r public.tenant_saas_plan_change_requests%rowtype;s public.tenant_saas_subscriptions%rowtype;b public.businesses%rowtype;e uuid;begin if not app.platform_has_permission('platform.subscriptions.manage') then raise exception 'plan change unavailable' using errcode='42501';end if;select id into e from public.tenant_saas_subscription_events where idempotency_key=trim(request_key);if e is not null then return e;end if;select * into r from public.tenant_saas_plan_change_requests where id=change_request_id_value for update;select * into s from public.tenant_saas_subscriptions where id=r.tenant_subscription_id for update;select * into b from public.businesses where id=r.business_id;if r.id is null or r.status<>'previewed' or s.saas_plan_version_id<>r.from_plan_version_id or r.preview_fingerprint<>preview_fingerprint_value or lower(trim(confirmation_value))<>b.public_slug then raise exception 'current confirmed plan preview required' using errcode='P0001';end if;if r.effective_timing='immediate' then update public.tenant_saas_subscriptions set saas_plan_version_id=r.to_plan_version_id,scheduled_saas_plan_version_id=null,scheduled_plan_effective_at=null,changed_by=auth.uid() where id=s.id;else update public.tenant_saas_subscriptions set scheduled_saas_plan_version_id=r.to_plan_version_id,scheduled_plan_effective_at=s.current_period_end,changed_by=auth.uid() where id=s.id;end if;update public.tenant_saas_plan_change_requests set status='applied',applied_at=now() where id=r.id;insert into public.tenant_saas_subscription_events(business_id,tenant_subscription_id,event_type,from_status,to_status,reason,actor_id,idempotency_key) values(r.business_id,s.id,'plan_changed',s.status,s.status,r.reason,auth.uid(),trim(request_key)) returning id into e;return e;end;$$;

create or replace function app.get_effective_tenant_entitlements(target_business_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$declare result jsonb;begin if not (app.platform_has_permission('platform.subscriptions.read') or app.is_business_member(target_business_id)) then raise exception 'entitlements unavailable' using errcode='42501';end if;with subscription as(select s.business_id,s.saas_plan_version_id from public.tenant_saas_subscriptions s where s.business_id=target_business_id),keys as(select e.entitlement_key from subscription s join public.saas_plan_entitlements e on e.saas_plan_version_id=s.saas_plan_version_id union select o.entitlement_key from public.tenant_entitlement_overrides o where o.business_id=target_business_id and now()>=o.starts_at and now()<o.expires_at) select coalesce(jsonb_object_agg(k.entitlement_key,jsonb_build_object('value',coalesce(o.value,e.value),'source',case when o.id is null then 'plan' else 'temporary_override' end,'expires_at',o.expires_at)),'{}'::jsonb) into result from keys k cross join subscription s left join public.saas_plan_entitlements e on e.saas_plan_version_id=s.saas_plan_version_id and e.entitlement_key=k.entitlement_key left join lateral(select x.id,x.value,x.expires_at from public.tenant_entitlement_overrides x where x.business_id=s.business_id and x.entitlement_key=k.entitlement_key and now()>=x.starts_at and now()<x.expires_at order by x.created_at desc limit 1)o on true;return result;end;$$;
revoke all on function app.get_effective_tenant_entitlements(uuid) from public;grant execute on function app.get_effective_tenant_entitlements(uuid) to authenticated;
