-- PetCare E08 Stripe-hosted invoice checkout and idempotent webhook posting.
alter table public.payment_requests add column provider_session_reference text;
create unique index payment_request_provider_session_idx on public.payment_requests(provider,provider_session_reference) where provider_session_reference is not null;
create unique index payment_provider_reference_idx on public.payments(provider,provider_reference) where provider_reference is not null;

create or replace function app.create_stripe_payment_request(target_business_id uuid,target_invoice_id uuid,amount_value bigint,request_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare existing uuid;i public.invoices%rowtype;bal public.invoice_balances%rowtype;merchant public.merchant_accounts%rowtype;created_id uuid;purpose_value text;begin
 if not app.member_has_permission(target_business_id,'payments.collect') then raise exception 'online payment unavailable' using errcode='42501';end if;
 select id into existing from public.payment_requests where business_id=target_business_id and idempotency_key=trim(request_key);if existing is not null then return existing;end if;
 select * into i from public.invoices where business_id=target_business_id and id=target_invoice_id;select * into bal from public.invoice_balances where business_id=target_business_id and invoice_id=i.id;select * into merchant from public.merchant_accounts where business_id=target_business_id and provider='stripe' and status='active' and charges_enabled;
 if i.id is null or i.status not in('open','partially_paid') or amount_value<=0 or amount_value>bal.balance_due_minor or merchant.id is null or not app.member_can_access_location(target_business_id,i.location_id) then raise exception 'online payment unavailable' using errcode='P0001';end if;
 purpose_value:=case when bal.paid_minor=0 and amount_value<=bal.deposit_required_minor then 'deposit' when amount_value=bal.balance_due_minor then 'balance' else 'partial' end;
 insert into public.payment_requests(business_id,invoice_id,booking_id,customer_id,purpose,amount_minor,currency_code,status,provider,idempotency_key) values(target_business_id,i.id,i.booking_id,i.customer_id,purpose_value,amount_value,i.currency_code,'created','stripe',trim(request_key)) returning id into created_id;return created_id;end;$$;

create or replace function app.attach_stripe_checkout_session(target_request_id uuid,session_reference text) returns void language plpgsql security definer set search_path='' as $$begin
 if trim(session_reference)!~'^cs_' then raise exception 'invalid checkout session' using errcode='22023';end if;update public.payment_requests set provider_session_reference=trim(session_reference),status='action_required' where id=target_request_id and provider='stripe' and status in('created','action_required');if not found then raise exception 'payment request unavailable' using errcode='P0002';end if;end;$$;

create or replace function app.process_stripe_checkout_event(target_event_id uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare e public.processor_webhook_events%rowtype;payload jsonb;object_value jsonb;request_id uuid;pr public.payment_requests%rowtype;i public.invoices%rowtype;bal public.invoice_balances%rowtype;payment_id uuid;receipt_id uuid;amount_value bigint;currency_value text;session_id text;intent_id text;allocation_kind text;booking_status text;begin
 select * into e from public.processor_webhook_events where id=target_event_id for update;if e.status='processed' then select id into payment_id from public.payments where business_id=e.business_id and provider='stripe' and provider_reference=(select raw_payload#>>'{data,object,payment_intent}' from public.processor_webhook_payloads where webhook_event_id=e.id);return payment_id;end if;
 if e.id is null or e.status<>'pending' or e.event_type<>'checkout.session.completed' or e.business_id is null then raise exception 'processable checkout event unavailable' using errcode='P0002';end if;
 select raw_payload into payload from public.processor_webhook_payloads where webhook_event_id=e.id;object_value:=payload#>'{data,object}';request_id:=nullif(object_value#>>'{metadata,petcare_payment_request_id}','')::uuid;amount_value:=(object_value->>'amount_total')::bigint;currency_value:=upper(object_value->>'currency');session_id:=object_value->>'id';intent_id:=object_value->>'payment_intent';
 select * into pr from public.payment_requests where id=request_id and business_id=e.business_id for update;select * into i from public.invoices where business_id=pr.business_id and id=pr.invoice_id for update;
 if pr.id is null or pr.provider_session_reference<>session_id or pr.amount_minor<>amount_value or pr.currency_code<>currency_value or object_value->>'payment_status'<>'paid' then raise exception 'checkout event correlation failed' using errcode='P0001';end if;
 select id into payment_id from public.payments where business_id=pr.business_id and payment_request_id=pr.id;if payment_id is not null then update public.processor_webhook_events set status='processed',processed_at=now() where id=e.id;return payment_id;end if;
 select * into bal from public.invoice_balances where business_id=i.business_id and invoice_id=i.id;allocation_kind:=case when bal.paid_minor=0 and amount_value<=bal.deposit_required_minor then 'deposit' when amount_value=bal.balance_due_minor then 'balance' else 'partial' end;
 insert into public.payments(business_id,payment_request_id,invoice_id,location_id,amount_minor,currency_code,tender_type,status,provider,provider_reference) values(pr.business_id,pr.id,i.id,i.location_id,amount_value,pr.currency_code,'stripe_card','succeeded','stripe',intent_id) returning id into payment_id;
 insert into public.payment_allocations(business_id,payment_id,invoice_id,amount_minor,allocation_type) values(pr.business_id,payment_id,i.id,amount_value,allocation_kind);update public.payment_requests set status='succeeded',provider_reference=intent_id where id=pr.id;
 select * into bal from public.invoice_balances where business_id=i.business_id and invoice_id=i.id;update public.invoices set status=case when bal.balance_due_minor=0 then 'paid' else 'partially_paid' end where id=i.id;
 insert into public.receipts(business_id,invoice_id,payment_id,receipt_number,amount_minor,currency_code) values(pr.business_id,i.id,payment_id,i.invoice_number||'-P'||substr(payment_id::text,1,8),amount_value,i.currency_code) returning id into receipt_id;
 insert into public.transactional_message_outbox(business_id,customer_id,booking_id,invoice_id,message_type,channel,template_data,idempotency_key) values(pr.business_id,i.customer_id,i.booking_id,i.id,'payment_receipt','email',jsonb_build_object('receipt_id',receipt_id,'invoice_number',i.invoice_number,'amount_minor',amount_value,'currency_code',i.currency_code),'payment-receipt-'||payment_id::text);
 if i.booking_id is not null then select status into booking_status from public.bookings where business_id=pr.business_id and id=i.booking_id;if booking_status='pending_deposit' and bal.deposit_due_minor=0 then perform app.confirm_booking_deposit(pr.business_id,i.booking_id,payment_id::text,'ledger-deposit-'||payment_id::text);update public.booking_action_items set status='resolved',resolved_by=null,resolved_at=now() where business_id=pr.business_id and booking_id=i.booking_id and action_type='deposit' and status='open';end if;end if;
 update public.processor_webhook_events set status='processed',processed_at=now(),attempt_count=attempt_count+1 where id=e.id;return payment_id;end;$$;

revoke all on function app.create_stripe_payment_request(uuid,uuid,bigint,text),app.attach_stripe_checkout_session(uuid,text),app.process_stripe_checkout_event(uuid) from public;
grant execute on function app.create_stripe_payment_request(uuid,uuid,bigint,text) to authenticated;grant execute on function app.attach_stripe_checkout_session(uuid,text),app.process_stripe_checkout_event(uuid) to service_role;
