-- PetCare E12 website launch controls, inquiries, and crawl projections.
create table public.website_inquiries(
 id uuid primary key default gen_random_uuid(),business_id uuid not null,name text not null check(char_length(trim(name)) between 2 and 120),email text not null check(email=lower(trim(email)) and position('@' in email)>1),phone text,message text not null check(char_length(trim(message)) between 10 and 3000),consent boolean not null,source_path text not null,submitted_at timestamptz not null default now(),status text not null default 'new' check(status in('new','in_review','responded','closed','spam')),idempotency_key text not null,
 unique(business_id,id),unique(business_id,idempotency_key),foreign key(business_id) references public.businesses(id) on delete restrict
);
create trigger website_inquiries_tenant before update on public.website_inquiries for each row execute function app.prevent_business_id_change();create trigger website_inquiries_audit after insert or update or delete on public.website_inquiries for each row execute function app.audit_configuration_change('website.inquiry.changed','website_inquiry');

create or replace function app.unpublish_tenant_website(target_business_id uuid)
returns void language plpgsql security definer set search_path='' as $$begin if not app.member_has_permission(target_business_id,'website.publish') then raise exception 'website publishing unavailable' using errcode='42501';end if;update public.tenant_websites set status='unpublished' where business_id=target_business_id and status='published';if not found then raise exception 'published website unavailable' using errcode='P0002';end if;end;$$;
create or replace function app.get_tenant_website_draft_preview(target_business_id uuid)
returns jsonb language sql security definer stable set search_path='' as $$select jsonb_build_object('business',jsonb_build_object('name',b.name,'slug',b.public_slug),'theme_key',w.theme_key,'brand_tokens',w.brand_tokens,'content',w.draft_content,'services',coalesce((select jsonb_agg(jsonb_build_object('name',sv.customer_name,'description',sv.short_description,'category',s.category) order by s.display_order) from public.services s join public.service_versions sv on sv.business_id=s.business_id and sv.service_id=s.id and sv.status='published' where s.business_id=b.id and s.status='active'),'[]'::jsonb)) from public.businesses b join public.tenant_websites w on w.business_id=b.id where b.id=target_business_id and app.member_has_permission(b.id,'website.edit')$$;
create or replace function app.get_tenant_website_readiness(target_business_id uuid)
returns jsonb language sql security definer stable set search_path='' as $$select jsonb_build_object('hero',char_length(trim(coalesce(w.draft_content->>'hero_title','')))>=5 and char_length(trim(coalesce(w.draft_content->>'hero_body','')))>=12,'about',char_length(trim(coalesce(w.draft_content->>'about','')))>=12,'faq',jsonb_typeof(w.draft_content->'faqs')='array' and jsonb_array_length(w.draft_content->'faqs')>0,'contact',position('@' in coalesce(w.draft_content->>'contact_email',''))>1,'brand',coalesce(w.brand_tokens->>'primary','')~'^#[0-9A-Fa-f]{6}$' and coalesce(w.brand_tokens->>'accent','')~'^#[0-9A-Fa-f]{6}$') from public.tenant_websites w where w.business_id=target_business_id and app.member_has_permission(w.business_id,'website.edit')$$;
create or replace function app.submit_website_inquiry(public_slug_value text,name_value text,email_value text,phone_value text,message_value text,consent_value boolean,source_value text,honeypot_value text,request_key text)
returns uuid language plpgsql security definer set search_path='' as $$declare business_id_value uuid;created_id uuid;begin select b.id into business_id_value from public.businesses b join public.tenant_websites w on w.business_id=b.id where b.public_slug=lower(trim(public_slug_value)) and b.status='active' and w.status='published';if business_id_value is null or not consent_value or char_length(trim(coalesce(honeypot_value,'')))>0 or char_length(trim(coalesce(name_value,'')))<2 or position('@' in lower(trim(coalesce(email_value,''))))<=1 or char_length(trim(coalesce(message_value,'')))<10 then raise exception 'inquiry unavailable' using errcode='22023';end if;select id into created_id from public.website_inquiries where business_id=business_id_value and idempotency_key=trim(request_key);if created_id is not null then return created_id;end if;insert into public.website_inquiries(business_id,name,email,phone,message,consent,source_path,idempotency_key) values(business_id_value,trim(name_value),lower(trim(email_value)),nullif(trim(phone_value),''),trim(message_value),true,left(trim(source_value),500),trim(request_key)) returning id into created_id;return created_id;end;$$;

alter table public.website_inquiries enable row level security;alter table public.website_inquiries force row level security;revoke all on public.website_inquiries from anon,authenticated;grant select on public.website_inquiries to authenticated;create policy website_inquiries_staff on public.website_inquiries for select to authenticated using(app.member_has_permission(business_id,'website.edit'));
revoke all on function app.unpublish_tenant_website(uuid),app.get_tenant_website_draft_preview(uuid),app.get_tenant_website_readiness(uuid),app.submit_website_inquiry(text,text,text,text,text,boolean,text,text,text) from public;grant execute on function app.unpublish_tenant_website(uuid),app.get_tenant_website_draft_preview(uuid),app.get_tenant_website_readiness(uuid) to authenticated;grant execute on function app.submit_website_inquiry(text,text,text,text,text,boolean,text,text,text) to anon,authenticated;
