-- PetCare E14 SaaS subscription projection, separate from tenant customer commerce.
alter table public.platform_permission_definitions drop constraint platform_permission_definitions_permission_key_check;
alter table public.platform_permission_definitions add constraint platform_permission_definitions_permission_key_check check(permission_key in('platform.businesses.read','platform.businesses.manage','platform.audit.read','platform.subscriptions.read','platform.subscriptions.manage'));
insert into public.platform_permission_definitions values('platform.subscriptions.read','View SaaS plan and tenant subscription metadata.'),('platform.subscriptions.manage','Assign and progress tenant SaaS subscriptions.');
insert into public.platform_role_permissions values('platform_admin','platform.subscriptions.read'),('platform_admin','platform.subscriptions.manage'),('platform_support','platform.subscriptions.read'),('platform_auditor','platform.subscriptions.read');

create table public.saas_plans(id uuid primary key default gen_random_uuid(),plan_key text not null unique check(plan_key~'^[a-z][a-z0-9_]*$'),display_name text not null,status text not null check(status in('draft','active','retired')),created_at timestamptz not null default now());
create table public.saas_plan_versions(id uuid primary key default gen_random_uuid(),saas_plan_id uuid not null references public.saas_plans(id) on delete restrict,version_number integer not null check(version_number>0),status text not null check(status in('draft','active','superseded','retired')),currency_code text not null check(currency_code~'^[A-Z]{3}$'),billing_interval text not null check(billing_interval in('month','year')),unit_amount_minor bigint not null check(unit_amount_minor>=0),trial_days integer not null default 0 check(trial_days between 0 and 90),effective_from timestamptz,created_at timestamptz not null default now(),unique(saas_plan_id,version_number));
create unique index saas_plan_one_active_version_idx on public.saas_plan_versions(saas_plan_id) where status='active';
create table public.saas_plan_entitlements(id uuid primary key default gen_random_uuid(),saas_plan_version_id uuid not null references public.saas_plan_versions(id) on delete restrict,entitlement_key text not null check(entitlement_key~'^[a-z][a-z0-9_.]*$'),value jsonb not null,created_at timestamptz not null default now(),unique(saas_plan_version_id,entitlement_key));
create table public.tenant_saas_subscriptions(id uuid primary key default gen_random_uuid(),business_id uuid not null unique references public.businesses(id) on delete restrict,saas_plan_version_id uuid not null references public.saas_plan_versions(id) on delete restrict,status text not null check(status in('trialing','active','past_due','cancel_scheduled','cancelled')),provider text not null default 'manual' check(provider in('manual','stripe')),provider_customer_reference text,provider_subscription_reference text,current_period_start timestamptz not null,current_period_end timestamptz not null,trial_ends_at timestamptz,cancel_at_period_end boolean not null default false,changed_by uuid not null references public.identity_profiles(id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(current_period_end>current_period_start));
create table public.tenant_saas_subscription_events(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete restrict,tenant_subscription_id uuid not null references public.tenant_saas_subscriptions(id) on delete restrict,event_type text not null check(event_type in('assigned','state_changed','plan_changed')),from_status text,to_status text not null,reason text not null,actor_id uuid not null references public.identity_profiles(id) on delete restrict,occurred_at timestamptz not null default now(),idempotency_key text not null unique);
create trigger tenant_saas_subscriptions_updated before update on public.tenant_saas_subscriptions for each row execute function app.set_updated_at();
create trigger tenant_saas_events_immutable before update or delete on public.tenant_saas_subscription_events for each row execute function app.prevent_commercial_snapshot_change();
with plan as(insert into public.saas_plans(plan_key,display_name,status) values('starter','Starter','active') returning id),version as(insert into public.saas_plan_versions(saas_plan_id,version_number,status,currency_code,billing_interval,unit_amount_minor,trial_days,effective_from) select id,1,'active','USD','month',9900,14,now() from plan returning id)
insert into public.saas_plan_entitlements(saas_plan_version_id,entitlement_key,value) select id,key,value from version cross join lateral jsonb_each(jsonb_build_object('locations.max',1,'staff.max',10,'website.custom_domain',false,'reports.level','standard','sms.monthly_included',0)) on conflict do nothing;

create or replace function app.list_saas_plans() returns jsonb language plpgsql security definer set search_path='' as $$begin if not app.platform_has_permission('platform.subscriptions.read') then raise exception 'SaaS plans unavailable' using errcode='42501';end if;return coalesce((select jsonb_agg(jsonb_build_object('plan_key',p.plan_key,'display_name',p.display_name,'version_id',v.id,'version_number',v.version_number,'currency_code',v.currency_code,'billing_interval',v.billing_interval,'unit_amount_minor',v.unit_amount_minor,'trial_days',v.trial_days,'entitlements',(select jsonb_object_agg(e.entitlement_key,e.value) from public.saas_plan_entitlements e where e.saas_plan_version_id=v.id)) order by p.display_name) from public.saas_plans p join public.saas_plan_versions v on v.saas_plan_id=p.id and v.status='active' where p.status='active'),'[]'::jsonb);end;$$;
create or replace function app.list_tenant_saas_subscriptions() returns jsonb language plpgsql security definer set search_path='' as $$begin if not app.platform_has_permission('platform.subscriptions.read') then raise exception 'tenant SaaS subscriptions unavailable' using errcode='42501';end if;return coalesce((select jsonb_agg(jsonb_build_object('business_id',b.id,'business_name',b.name,'public_slug',b.public_slug,'subscription_id',s.id,'status',s.status,'plan_key',p.plan_key,'plan_name',p.display_name,'unit_amount_minor',v.unit_amount_minor,'currency_code',v.currency_code,'billing_interval',v.billing_interval,'current_period_start',s.current_period_start,'current_period_end',s.current_period_end,'trial_ends_at',s.trial_ends_at,'cancel_at_period_end',s.cancel_at_period_end,'entitlements',(select jsonb_object_agg(e.entitlement_key,e.value) from public.saas_plan_entitlements e where e.saas_plan_version_id=v.id)) order by b.name) from public.businesses b left join public.tenant_saas_subscriptions s on s.business_id=b.id left join public.saas_plan_versions v on v.id=s.saas_plan_version_id left join public.saas_plans p on p.id=v.saas_plan_id),'[]'::jsonb);end;$$;
create or replace function app.assign_tenant_saas_subscription(target_business_id uuid,target_plan_version_id uuid,start_as_trial boolean,reason_value text,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare subscription_id uuid;event_id uuid;version public.saas_plan_versions%rowtype;start_value timestamptz:=now();status_value text;begin if not app.platform_has_permission('platform.subscriptions.manage') then raise exception 'SaaS subscription management unavailable' using errcode='42501';end if;select tenant_subscription_id into subscription_id from public.tenant_saas_subscription_events where idempotency_key=trim(request_key);if subscription_id is not null then return subscription_id;end if;select * into version from public.saas_plan_versions where id=target_plan_version_id and status='active';if version.id is null or not exists(select 1 from public.businesses where id=target_business_id) or exists(select 1 from public.tenant_saas_subscriptions where business_id=target_business_id) or char_length(trim(coalesce(reason_value,'')))<12 then raise exception 'documented new SaaS subscription required' using errcode='22023';end if;status_value:=case when start_as_trial and version.trial_days>0 then 'trialing' else 'active' end;insert into public.tenant_saas_subscriptions(business_id,saas_plan_version_id,status,current_period_start,current_period_end,trial_ends_at,changed_by) values(target_business_id,version.id,status_value,start_value,start_value+case version.billing_interval when 'year' then interval '1 year' else interval '1 month' end,case when status_value='trialing' then start_value+make_interval(days=>version.trial_days) end,auth.uid()) returning id into subscription_id;insert into public.tenant_saas_subscription_events(business_id,tenant_subscription_id,event_type,to_status,reason,actor_id,idempotency_key) values(target_business_id,subscription_id,'assigned',status_value,trim(reason_value),auth.uid(),trim(request_key)) returning id into event_id;return subscription_id;end;$$;
create or replace function app.transition_tenant_saas_subscription(target_business_id uuid,next_status_value text,reason_value text,request_key text) returns uuid language plpgsql security definer set search_path='' as $$declare subscription public.tenant_saas_subscriptions%rowtype;event_id uuid;begin if not app.platform_has_permission('platform.subscriptions.manage') then raise exception 'SaaS subscription management unavailable' using errcode='42501';end if;select id into event_id from public.tenant_saas_subscription_events where idempotency_key=trim(request_key);if event_id is not null then return event_id;end if;select * into subscription from public.tenant_saas_subscriptions where business_id=target_business_id for update;if subscription.id is null or char_length(trim(coalesce(reason_value,'')))<12 or (subscription.status,next_status_value) not in(('trialing','active'),('trialing','cancelled'),('active','past_due'),('active','cancel_scheduled'),('past_due','active'),('past_due','cancel_scheduled'),('cancel_scheduled','active'),('cancel_scheduled','cancelled')) then raise exception 'controlled SaaS subscription transition required' using errcode='P0001';end if;update public.tenant_saas_subscriptions set status=next_status_value,cancel_at_period_end=next_status_value='cancel_scheduled',changed_by=auth.uid() where id=subscription.id;insert into public.tenant_saas_subscription_events(business_id,tenant_subscription_id,event_type,from_status,to_status,reason,actor_id,idempotency_key) values(target_business_id,subscription.id,'state_changed',subscription.status,next_status_value,trim(reason_value),auth.uid(),trim(request_key)) returning id into event_id;return event_id;end;$$;

do $$declare n text;begin foreach n in array array['saas_plans','saas_plan_versions','saas_plan_entitlements','tenant_saas_subscriptions','tenant_saas_subscription_events'] loop execute format('alter table public.%I enable row level security',n);execute format('alter table public.%I force row level security',n);execute format('revoke all on public.%I from anon,authenticated',n);end loop;end$$;
grant select on public.saas_plans,public.saas_plan_versions,public.saas_plan_entitlements,public.tenant_saas_subscriptions,public.tenant_saas_subscription_events to authenticated;
create policy saas_plans_operator on public.saas_plans for select to authenticated using(app.platform_has_permission('platform.subscriptions.read'));create policy saas_plan_versions_operator on public.saas_plan_versions for select to authenticated using(app.platform_has_permission('platform.subscriptions.read'));create policy saas_plan_entitlements_operator on public.saas_plan_entitlements for select to authenticated using(app.platform_has_permission('platform.subscriptions.read'));create policy tenant_saas_subscriptions_operator on public.tenant_saas_subscriptions for select to authenticated using(app.platform_has_permission('platform.subscriptions.read'));create policy tenant_saas_events_operator on public.tenant_saas_subscription_events for select to authenticated using(app.platform_has_permission('platform.audit.read'));
revoke all on function app.list_saas_plans(),app.list_tenant_saas_subscriptions(),app.assign_tenant_saas_subscription(uuid,uuid,boolean,text,text),app.transition_tenant_saas_subscription(uuid,text,text,text) from public;grant execute on function app.list_saas_plans(),app.list_tenant_saas_subscriptions(),app.assign_tenant_saas_subscription(uuid,uuid,boolean,text,text),app.transition_tenant_saas_subscription(uuid,text,text,text) to authenticated;
