-- PetCare E13 operational care compliance and safety guardrails.
alter table public.reporting_runs drop constraint reporting_runs_report_key_check;
alter table public.reporting_runs add constraint reporting_runs_report_key_check check(report_key in('business_summary','booking_activity','capacity_utilization','financial_reconciliation','care_compliance'));

create or replace function app.get_care_compliance_report(target_business_id uuid,period_start_value timestamptz,period_end_value timestamptz) returns jsonb language plpgsql security definer set search_path='' as $$
declare generated_at_value timestamptz:=clock_timestamp();run_id_value uuid;task_rows_value jsonb;incident_rows_value jsonb;summary_value jsonb;
begin
 if not app.member_has_permission(target_business_id,'reports.view_operational') then raise exception 'care compliance report unavailable' using errcode='42501';end if;
 if period_start_value is null or period_end_value is null or period_end_value<=period_start_value or period_end_value-period_start_value>interval '366 days' then raise exception 'valid report period required' using errcode='22023';end if;
 with scoped_tasks as(
  select t.*,completed_at between due_starts_at and due_ends_at on_time from public.care_tasks t where t.business_id=target_business_id and t.due_starts_at>=period_start_value and t.due_starts_at<period_end_value and t.status<>'cancelled' and app.member_can_access_location(t.business_id,t.location_id)
 ) select coalesce(jsonb_agg(jsonb_build_object('task_type',task_type,'due_count',due_count,'completed_count',completed_count,'on_time_count',on_time_count,'exception_count',exception_count,'open_count',open_count,'on_time_rate_percent',case when due_count>0 then round(on_time_count::numeric/due_count*100,1) else 0 end) order by task_type),'[]'::jsonb),
  jsonb_build_object('due_tasks',coalesce(sum(due_count),0),'completed_tasks',coalesce(sum(completed_count),0),'on_time_tasks',coalesce(sum(on_time_count),0),'exception_tasks',coalesce(sum(exception_count),0),'open_tasks',coalesce(sum(open_count),0),'on_time_rate_percent',case when coalesce(sum(due_count),0)>0 then round(sum(on_time_count)::numeric/sum(due_count)*100,1) else 0 end)
 into task_rows_value,summary_value from(select task_type,count(*) due_count,count(*) filter(where status='completed') completed_count,count(*) filter(where status='completed' and on_time) on_time_count,count(*) filter(where status in('partial','refused','held','missed','unable','adverse')) exception_count,count(*) filter(where status in('scheduled','in_progress')) open_count from scoped_tasks group by task_type) grouped;
 select coalesce(jsonb_agg(jsonb_build_object('severity',severity,'incident_count',incident_count,'unresolved_count',unresolved_count) order by case severity when 'critical' then 1 when 'serious' then 2 when 'minor' then 3 else 4 end),'[]'::jsonb) into incident_rows_value from(select severity,count(*) incident_count,count(*) filter(where status not in('resolved','closed')) unresolved_count from public.operational_incidents i where i.business_id=target_business_id and i.occurred_at>=period_start_value and i.occurred_at<period_end_value and app.member_can_access_location(i.business_id,i.location_id) group by severity) grouped;
 summary_value:=summary_value||jsonb_build_object(
  'incident_count',(select count(*) from public.operational_incidents i where i.business_id=target_business_id and i.occurred_at>=period_start_value and i.occurred_at<period_end_value and app.member_can_access_location(i.business_id,i.location_id)),
  'serious_or_critical_incidents',(select count(*) from public.operational_incidents i where i.business_id=target_business_id and i.occurred_at>=period_start_value and i.occurred_at<period_end_value and i.severity in('serious','critical') and app.member_can_access_location(i.business_id,i.location_id)),
  'report_cards_eligible',(select count(*) from public.report_cards r where r.business_id=target_business_id and r.created_at>=period_start_value and r.created_at<period_end_value and app.member_can_access_location(r.business_id,r.location_id)),
  'report_cards_published',(select count(*) from public.report_cards r where r.business_id=target_business_id and r.created_at>=period_start_value and r.created_at<period_end_value and r.status='published' and app.member_can_access_location(r.business_id,r.location_id)),
  'open_alerts_as_of',(select count(*) from public.operational_alerts a where a.business_id=target_business_id and a.status in('open','acknowledged') and app.member_can_access_location(a.business_id,a.location_id))
 );
 insert into public.reporting_runs(business_id,report_key,definition_version,period_start,period_end,time_basis,freshness_at,filters) values(target_business_id,'care_compliance',1,period_start_value,period_end_value,'UTC',generated_at_value,jsonb_build_object('location_scope','authorized','task_basis','due_starts_at','incident_basis','occurred_at')) returning id into run_id_value;
 return jsonb_build_object('run_id',run_id_value,'definition_version',1,'period',jsonb_build_object('start',period_start_value,'end',period_end_value,'time_basis','UTC'),'freshness',jsonb_build_object('status','current','as_of',generated_at_value),'summary',summary_value,'task_types',task_rows_value,'incidents',incident_rows_value,'definitions',jsonb_build_object('on_time_task_rate','Eligible tasks completed inside their configured due window divided by all eligible due tasks.','task_exception','Partial, refused, held, missed, unable, or adverse outcomes.','report_card_publish_rate','Published report cards divided by report cards created in the period.','open_alerts','Unresolved operational alerts as of the freshness watermark.'));
end;$$;
revoke all on function app.get_care_compliance_report(uuid,timestamptz,timestamptz) from public;grant execute on function app.get_care_compliance_report(uuid,timestamptz,timestamptz) to authenticated;
