-- PetCare E12 inquiry operations, custom-domain lifecycle, and customer brand projection.
create table public.website_inquiry_events(
 id uuid primary key default gen_random_uuid(),business_id uuid not null,website_inquiry_id uuid not null,event_type text not null check(event_type in('review_started','responded','closed','marked_spam')),from_status text not null,to_status text not null,notes text not null,actor_id uuid not null references auth.users(id) on delete restrict default auth.uid(),occurred_at timestamptz not null default now(),idempotency_key text not null,
 unique(business_id,id),unique(business_id,idempotency_key),foreign key(business_id,website_inquiry_id) references public.website_inquiries(business_id,id) on delete restrict
);
create trigger website_inquiry_events_immutable before update or delete on public.website_inquiry_events for each row execute function app.prevent_commercial_snapshot_change();
create table public.tenant_domain_bindings(
 id uuid primary key default gen_random_uuid(),business_id uuid not null,hostname text not null unique check(hostname=lower(trim(hostname)) and hostname~'^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$'),status text not null default 'verification_pending' check(status in('verification_pending','verified','certificate_provisioning','active','degraded','disconnected')),verification_token text not null,requested_by uuid not null references auth.users(id) on delete restrict default auth.uid(),requested_at timestamptz not null default now(),verified_at timestamptz,last_checked_at timestamptz,last_result jsonb,disconnected_at timestamptz,
 unique(business_id,id),foreign key(business_id) references public.businesses(id) on delete restrict
);
create unique index tenant_domain_one_live_idx on public.tenant_domain_bindings(business_id) where status in('verification_pending','verified','certificate_provisioning','active','degraded');create trigger tenant_domains_tenant before update on public.tenant_domain_bindings for each row execute function app.prevent_business_id_change();create trigger tenant_domains_audit after insert or update or delete on public.tenant_domain_bindings for each row execute function app.audit_configuration_change('website.domain.changed','tenant_domain_binding');

create or replace function app.transition_website_inquiry(target_business_id uuid,target_inquiry_id uuid,new_status_value text,notes_value text,request_key text)
returns uuid language plpgsql security definer set search_path='' as $$declare inquiry public.website_inquiries%rowtype;event_id uuid;event_value text;begin if not app.member_has_permission(target_business_id,'website.edit') then raise exception 'inquiry review unavailable' using errcode='42501';end if;select id into event_id from public.website_inquiry_events where business_id=target_business_id and idempotency_key=trim(request_key);if event_id is not null then return event_id;end if;select * into inquiry from public.website_inquiries where business_id=target_business_id and id=target_inquiry_id for update;if inquiry.id is null or (inquiry.status,new_status_value) not in(('new','in_review'),('new','spam'),('in_review','responded'),('in_review','spam'),('responded','closed')) or char_length(trim(coalesce(notes_value,'')))<5 then raise exception 'invalid inquiry transition' using errcode='22023';end if;event_value:=case new_status_value when 'in_review' then 'review_started' when 'spam' then 'marked_spam' else new_status_value end;update public.website_inquiries set status=new_status_value where id=inquiry.id;insert into public.website_inquiry_events(business_id,website_inquiry_id,event_type,from_status,to_status,notes,idempotency_key) values(target_business_id,inquiry.id,event_value,inquiry.status,new_status_value,trim(notes_value),trim(request_key)) returning id into event_id;return event_id;end;$$;
create or replace function app.request_tenant_custom_domain(target_business_id uuid,hostname_value text)
returns uuid language plpgsql security definer set search_path='' as $$declare created_id uuid;normalized text:=lower(trim(hostname_value));begin if not app.member_has_permission(target_business_id,'website.publish') or normalized!~'^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$' then raise exception 'custom domain request unavailable' using errcode='22023';end if;update public.tenant_domain_bindings set status='disconnected',disconnected_at=now() where business_id=target_business_id and status in('verification_pending','verified','certificate_provisioning','active','degraded');insert into public.tenant_domain_bindings(business_id,hostname,verification_token) values(target_business_id,normalized,'petcare-verification='||pg_catalog.encode(extensions.gen_random_bytes(18),'hex')) returning id into created_id;return created_id;end;$$;
create or replace function app.record_tenant_domain_verification(target_binding_id uuid,verified_value boolean,evidence_value jsonb)
returns void language plpgsql security definer set search_path='' as $$begin update public.tenant_domain_bindings set status=case when verified_value then 'verified' else 'verification_pending' end,verified_at=case when verified_value then now() else null end,last_checked_at=now(),last_result=evidence_value where id=target_binding_id and status in('verification_pending','verified','degraded');if not found then raise exception 'domain verification unavailable' using errcode='P0002';end if;end;$$;
create or replace function app.get_customer_portal_brand(target_business_id uuid)
returns jsonb language sql security definer stable set search_path='' as $$select jsonb_build_object('business_name',b.name,'public_slug',b.public_slug,'theme_key',coalesce(p.theme_key,w.theme_key),'brand_tokens',coalesce(p.brand_tokens,w.brand_tokens)) from public.customer_portal_access a join public.businesses b on b.id=a.business_id left join public.tenant_websites w on w.business_id=b.id left join public.tenant_website_publications p on p.business_id=w.business_id and p.tenant_website_id=w.id and p.publication_number=w.current_publication_number where a.business_id=target_business_id and a.identity_id=auth.uid() and a.status='active'$$;

do $$declare n text;begin foreach n in array array['website_inquiry_events','tenant_domain_bindings'] loop execute format('alter table public.%I enable row level security',n);execute format('alter table public.%I force row level security',n);execute format('revoke all on public.%I from anon,authenticated',n);execute format('grant select on public.%I to authenticated',n);end loop;end$$;create policy website_inquiry_events_staff on public.website_inquiry_events for select to authenticated using(app.member_has_permission(business_id,'website.edit'));create policy tenant_domain_bindings_staff on public.tenant_domain_bindings for select to authenticated using(app.member_has_permission(business_id,'website.edit'));
revoke all on function app.transition_website_inquiry(uuid,uuid,text,text,text),app.request_tenant_custom_domain(uuid,text),app.record_tenant_domain_verification(uuid,boolean,jsonb),app.get_customer_portal_brand(uuid) from public;grant execute on function app.transition_website_inquiry(uuid,uuid,text,text,text),app.request_tenant_custom_domain(uuid,text),app.get_customer_portal_brand(uuid) to authenticated;grant execute on function app.record_tenant_domain_verification(uuid,boolean,jsonb) to service_role;
