-- PetCare E08 Stripe-hosted connected-account onboarding synchronization.
alter table public.merchant_accounts add column requirements_currently_due jsonb not null default '[]'::jsonb check(jsonb_typeof(requirements_currently_due)='array'),add column disabled_reason text;
create or replace function app.sync_stripe_merchant_account(target_business_id uuid,account_reference text,charges_value boolean,payouts_value boolean,details_value boolean,capabilities_value jsonb,requirements_value jsonb,disabled_reason_value text)
returns uuid language plpgsql security definer set search_path='' as $$declare merchant_id uuid;new_status text;begin
 if trim(account_reference)!~'^acct_[A-Za-z0-9]+$' or jsonb_typeof(capabilities_value)<>'object' or jsonb_typeof(requirements_value)<>'array' then raise exception 'invalid merchant synchronization' using errcode='22023';end if;
 new_status:=case when charges_value and payouts_value then 'active' when details_value or jsonb_array_length(requirements_value)>0 then 'restricted' else 'pending' end;
 insert into public.merchant_accounts(business_id,provider,provider_account_id,status,charges_enabled,payouts_enabled,details_submitted,dashboard_access,requirements_collector,fees_payer,losses_payer,capability_snapshot,requirements_currently_due,disabled_reason,last_synced_at)
 values(target_business_id,'stripe',trim(account_reference),new_status,charges_value,payouts_value,details_value,'express','stripe','account','stripe',capabilities_value,requirements_value,nullif(trim(disabled_reason_value),''),now())
 on conflict(business_id,provider) do update set provider_account_id=excluded.provider_account_id,status=excluded.status,charges_enabled=excluded.charges_enabled,payouts_enabled=excluded.payouts_enabled,details_submitted=excluded.details_submitted,capability_snapshot=excluded.capability_snapshot,requirements_currently_due=excluded.requirements_currently_due,disabled_reason=excluded.disabled_reason,last_synced_at=excluded.last_synced_at returning id into merchant_id;return merchant_id;end;$$;
revoke all on function app.sync_stripe_merchant_account(uuid,text,boolean,boolean,boolean,jsonb,jsonb,text) from public;grant execute on function app.sync_stripe_merchant_account(uuid,text,boolean,boolean,boolean,jsonb,jsonb,text) to service_role;
